// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: waCommonParameterised/WACommonParameterised.proto

package waCommonParameterised

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FutureProofBehavior int32

const (
	FutureProofBehavior_PLACEHOLDER    FutureProofBehavior = 0
	FutureProofBehavior_NO_PLACEHOLDER FutureProofBehavior = 1
	FutureProofBehavior_IGNORE         FutureProofBehavior = 2
)

// Enum value maps for FutureProofBehavior.
var (
	FutureProofBehavior_name = map[int32]string{
		0: "PLACEHOLDER",
		1: "NO_PLACEHOLDER",
		2: "IGNORE",
	}
	FutureProofBehavior_value = map[string]int32{
		"PLACEHOLDER":    0,
		"NO_PLACEHOLDER": 1,
		"IGNORE":         2,
	}
)

func (x FutureProofBehavior) Enum() *FutureProofBehavior {
	p := new(FutureProofBehavior)
	*p = x
	return p
}

func (x FutureProofBehavior) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FutureProofBehavior) Descriptor() protoreflect.EnumDescriptor {
	return file_waCommonParameterised_WACommonParameterised_proto_enumTypes[0].Descriptor()
}

func (FutureProofBehavior) Type() protoreflect.EnumType {
	return &file_waCommonParameterised_WACommonParameterised_proto_enumTypes[0]
}

func (x FutureProofBehavior) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *FutureProofBehavior) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = FutureProofBehavior(num)
	return nil
}

// Deprecated: Use FutureProofBehavior.Descriptor instead.
func (FutureProofBehavior) EnumDescriptor() ([]byte, []int) {
	return file_waCommonParameterised_WACommonParameterised_proto_rawDescGZIP(), []int{0}
}

type Command_CommandType int32

const (
	Command_EVERYONE   Command_CommandType = 1
	Command_SILENT     Command_CommandType = 2
	Command_AI         Command_CommandType = 3
	Command_AI_IMAGINE Command_CommandType = 4
)

// Enum value maps for Command_CommandType.
var (
	Command_CommandType_name = map[int32]string{
		1: "EVERYONE",
		2: "SILENT",
		3: "AI",
		4: "AI_IMAGINE",
	}
	Command_CommandType_value = map[string]int32{
		"EVERYONE":   1,
		"SILENT":     2,
		"AI":         3,
		"AI_IMAGINE": 4,
	}
)

func (x Command_CommandType) Enum() *Command_CommandType {
	p := new(Command_CommandType)
	*p = x
	return p
}

func (x Command_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_waCommonParameterised_WACommonParameterised_proto_enumTypes[1].Descriptor()
}

func (Command_CommandType) Type() protoreflect.EnumType {
	return &file_waCommonParameterised_WACommonParameterised_proto_enumTypes[1]
}

func (x Command_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Command_CommandType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Command_CommandType(num)
	return nil
}

// Deprecated: Use Command_CommandType.Descriptor instead.
func (Command_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_waCommonParameterised_WACommonParameterised_proto_rawDescGZIP(), []int{1, 0}
}

type Mention_MentionType int32

const (
	Mention_PROFILE Mention_MentionType = 0
)

// Enum value maps for Mention_MentionType.
var (
	Mention_MentionType_name = map[int32]string{
		0: "PROFILE",
	}
	Mention_MentionType_value = map[string]int32{
		"PROFILE": 0,
	}
)

func (x Mention_MentionType) Enum() *Mention_MentionType {
	p := new(Mention_MentionType)
	*p = x
	return p
}

func (x Mention_MentionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mention_MentionType) Descriptor() protoreflect.EnumDescriptor {
	return file_waCommonParameterised_WACommonParameterised_proto_enumTypes[2].Descriptor()
}

func (Mention_MentionType) Type() protoreflect.EnumType {
	return &file_waCommonParameterised_WACommonParameterised_proto_enumTypes[2]
}

func (x Mention_MentionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Mention_MentionType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Mention_MentionType(num)
	return nil
}

// Deprecated: Use Mention_MentionType.Descriptor instead.
func (Mention_MentionType) EnumDescriptor() ([]byte, []int) {
	return file_waCommonParameterised_WACommonParameterised_proto_rawDescGZIP(), []int{2, 0}
}

type MessageKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteJID   *string `protobuf:"bytes,1,opt,name=remoteJID" json:"remoteJID,omitempty"`
	FromMe      *bool   `protobuf:"varint,2,opt,name=fromMe" json:"fromMe,omitempty"`
	ID          *string `protobuf:"bytes,3,opt,name=ID" json:"ID,omitempty"`
	Participant *string `protobuf:"bytes,4,opt,name=participant" json:"participant,omitempty"`
}

func (x *MessageKey) Reset() {
	*x = MessageKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waCommonParameterised_WACommonParameterised_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageKey) ProtoMessage() {}

func (x *MessageKey) ProtoReflect() protoreflect.Message {
	mi := &file_waCommonParameterised_WACommonParameterised_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageKey.ProtoReflect.Descriptor instead.
func (*MessageKey) Descriptor() ([]byte, []int) {
	return file_waCommonParameterised_WACommonParameterised_proto_rawDescGZIP(), []int{0}
}

func (x *MessageKey) GetRemoteJID() string {
	if x != nil && x.RemoteJID != nil {
		return *x.RemoteJID
	}
	return ""
}

func (x *MessageKey) GetFromMe() bool {
	if x != nil && x.FromMe != nil {
		return *x.FromMe
	}
	return false
}

func (x *MessageKey) GetID() string {
	if x != nil && x.ID != nil {
		return *x.ID
	}
	return ""
}

func (x *MessageKey) GetParticipant() string {
	if x != nil && x.Participant != nil {
		return *x.Participant
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandType     *Command_CommandType `protobuf:"varint,1,opt,name=commandType,enum=WACommonParameterised.Command_CommandType" json:"commandType,omitempty"`
	Offset          *uint32              `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Length          *uint32              `protobuf:"varint,3,opt,name=length" json:"length,omitempty"`
	ValidationToken *string              `protobuf:"bytes,4,opt,name=validationToken" json:"validationToken,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waCommonParameterised_WACommonParameterised_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_waCommonParameterised_WACommonParameterised_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_waCommonParameterised_WACommonParameterised_proto_rawDescGZIP(), []int{1}
}

func (x *Command) GetCommandType() Command_CommandType {
	if x != nil && x.CommandType != nil {
		return *x.CommandType
	}
	return Command_EVERYONE
}

func (x *Command) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *Command) GetLength() uint32 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

func (x *Command) GetValidationToken() string {
	if x != nil && x.ValidationToken != nil {
		return *x.ValidationToken
	}
	return ""
}

type Mention struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MentionType  *Mention_MentionType `protobuf:"varint,1,opt,name=mentionType,enum=WACommonParameterised.Mention_MentionType" json:"mentionType,omitempty"`
	MentionedJID *string              `protobuf:"bytes,2,opt,name=mentionedJID" json:"mentionedJID,omitempty"`
	Offset       *uint32              `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	Length       *uint32              `protobuf:"varint,4,opt,name=length" json:"length,omitempty"`
}

func (x *Mention) Reset() {
	*x = Mention{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waCommonParameterised_WACommonParameterised_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mention) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mention) ProtoMessage() {}

func (x *Mention) ProtoReflect() protoreflect.Message {
	mi := &file_waCommonParameterised_WACommonParameterised_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mention.ProtoReflect.Descriptor instead.
func (*Mention) Descriptor() ([]byte, []int) {
	return file_waCommonParameterised_WACommonParameterised_proto_rawDescGZIP(), []int{2}
}

func (x *Mention) GetMentionType() Mention_MentionType {
	if x != nil && x.MentionType != nil {
		return *x.MentionType
	}
	return Mention_PROFILE
}

func (x *Mention) GetMentionedJID() string {
	if x != nil && x.MentionedJID != nil {
		return *x.MentionedJID
	}
	return ""
}

func (x *Mention) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *Mention) GetLength() uint32 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

type MessageText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text         *string    `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	MentionedJID []string   `protobuf:"bytes,2,rep,name=mentionedJID" json:"mentionedJID,omitempty"`
	Commands     []*Command `protobuf:"bytes,3,rep,name=commands" json:"commands,omitempty"`
	Mentions     []*Mention `protobuf:"bytes,4,rep,name=mentions" json:"mentions,omitempty"`
}

func (x *MessageText) Reset() {
	*x = MessageText{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waCommonParameterised_WACommonParameterised_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageText) ProtoMessage() {}

func (x *MessageText) ProtoReflect() protoreflect.Message {
	mi := &file_waCommonParameterised_WACommonParameterised_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageText.ProtoReflect.Descriptor instead.
func (*MessageText) Descriptor() ([]byte, []int) {
	return file_waCommonParameterised_WACommonParameterised_proto_rawDescGZIP(), []int{3}
}

func (x *MessageText) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *MessageText) GetMentionedJID() []string {
	if x != nil {
		return x.MentionedJID
	}
	return nil
}

func (x *MessageText) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *MessageText) GetMentions() []*Mention {
	if x != nil {
		return x.Mentions
	}
	return nil
}

type SubProtocol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	Version *int32 `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
}

func (x *SubProtocol) Reset() {
	*x = SubProtocol{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waCommonParameterised_WACommonParameterised_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubProtocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubProtocol) ProtoMessage() {}

func (x *SubProtocol) ProtoReflect() protoreflect.Message {
	mi := &file_waCommonParameterised_WACommonParameterised_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubProtocol.ProtoReflect.Descriptor instead.
func (*SubProtocol) Descriptor() ([]byte, []int) {
	return file_waCommonParameterised_WACommonParameterised_proto_rawDescGZIP(), []int{4}
}

func (x *SubProtocol) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SubProtocol) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

var File_waCommonParameterised_WACommonParameterised_proto protoreflect.FileDescriptor

var file_waCommonParameterised_WACommonParameterised_proto_rawDesc = []byte{
	0x0a, 0x31, 0x77, 0x61, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x69, 0x73, 0x65, 0x64, 0x2f, 0x57, 0x41, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x69, 0x73, 0x65, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x15, 0x57, 0x41, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x69, 0x73, 0x65, 0x64, 0x22, 0x74, 0x0a, 0x0a, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x4a, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x4a, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x4d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x4d, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x20,
	0x0a, 0x0b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74,
	0x22, 0xf2, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x4c, 0x0a, 0x0b,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x2a, 0x2e, 0x57, 0x41, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x69, 0x73, 0x65, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x28, 0x0a, 0x0f, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x3f, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x56, 0x45, 0x52, 0x59, 0x4f, 0x4e, 0x45, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x49, 0x4c, 0x45, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x06, 0x0a,
	0x02, 0x41, 0x49, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x49, 0x5f, 0x49, 0x4d, 0x41, 0x47,
	0x49, 0x4e, 0x45, 0x10, 0x04, 0x22, 0xc7, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x6e, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x4c, 0x0a, 0x0b, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x57, 0x41, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x69, 0x73, 0x65, 0x64, 0x2e, 0x4d,
	0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x65, 0x64, 0x4a, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x65, 0x64,
	0x4a, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x65, 0x6e,
	0x67, 0x74, 0x68, 0x22, 0x1a, 0x0a, 0x0b, 0x4d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x4f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x00, 0x22,
	0xbd, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x65, 0x78, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x65, 0x64,
	0x4a, 0x49, 0x44, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x65, 0x6e, 0x74, 0x69,
	0x6f, 0x6e, 0x65, 0x64, 0x4a, 0x49, 0x44, 0x12, 0x3a, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x57, 0x41, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x69, 0x73, 0x65,
	0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x73, 0x12, 0x3a, 0x0a, 0x08, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x57, 0x41, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x69, 0x73, 0x65, 0x64, 0x2e, 0x4d, 0x65,
	0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x41, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x2a, 0x46, 0x0a, 0x13, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x6f,
	0x66, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x4c, 0x41,
	0x43, 0x45, 0x48, 0x4f, 0x4c, 0x44, 0x45, 0x52, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4e, 0x4f,
	0x5f, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x48, 0x4f, 0x4c, 0x44, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x49, 0x47, 0x4e, 0x4f, 0x52, 0x45, 0x10, 0x02, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x6f,
	0x2e, 0x6d, 0x61, 0x75, 0x2e, 0x66, 0x69, 0x2f, 0x77, 0x68, 0x61, 0x74, 0x73, 0x6d, 0x65, 0x6f,
	0x77, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x69, 0x73, 0x65, 0x64,
}

var (
	file_waCommonParameterised_WACommonParameterised_proto_rawDescOnce sync.Once
	file_waCommonParameterised_WACommonParameterised_proto_rawDescData = file_waCommonParameterised_WACommonParameterised_proto_rawDesc
)

func file_waCommonParameterised_WACommonParameterised_proto_rawDescGZIP() []byte {
	file_waCommonParameterised_WACommonParameterised_proto_rawDescOnce.Do(func() {
		file_waCommonParameterised_WACommonParameterised_proto_rawDescData = protoimpl.X.CompressGZIP(file_waCommonParameterised_WACommonParameterised_proto_rawDescData)
	})
	return file_waCommonParameterised_WACommonParameterised_proto_rawDescData
}

var file_waCommonParameterised_WACommonParameterised_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_waCommonParameterised_WACommonParameterised_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_waCommonParameterised_WACommonParameterised_proto_goTypes = []interface{}{
	(FutureProofBehavior)(0), // 0: WACommonParameterised.FutureProofBehavior
	(Command_CommandType)(0), // 1: WACommonParameterised.Command.CommandType
	(Mention_MentionType)(0), // 2: WACommonParameterised.Mention.MentionType
	(*MessageKey)(nil),       // 3: WACommonParameterised.MessageKey
	(*Command)(nil),          // 4: WACommonParameterised.Command
	(*Mention)(nil),          // 5: WACommonParameterised.Mention
	(*MessageText)(nil),      // 6: WACommonParameterised.MessageText
	(*SubProtocol)(nil),      // 7: WACommonParameterised.SubProtocol
}
var file_waCommonParameterised_WACommonParameterised_proto_depIdxs = []int32{
	1, // 0: WACommonParameterised.Command.commandType:type_name -> WACommonParameterised.Command.CommandType
	2, // 1: WACommonParameterised.Mention.mentionType:type_name -> WACommonParameterised.Mention.MentionType
	4, // 2: WACommonParameterised.MessageText.commands:type_name -> WACommonParameterised.Command
	5, // 3: WACommonParameterised.MessageText.mentions:type_name -> WACommonParameterised.Mention
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_waCommonParameterised_WACommonParameterised_proto_init() }
func file_waCommonParameterised_WACommonParameterised_proto_init() {
	if File_waCommonParameterised_WACommonParameterised_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_waCommonParameterised_WACommonParameterised_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waCommonParameterised_WACommonParameterised_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waCommonParameterised_WACommonParameterised_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mention); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waCommonParameterised_WACommonParameterised_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageText); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waCommonParameterised_WACommonParameterised_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubProtocol); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_waCommonParameterised_WACommonParameterised_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_waCommonParameterised_WACommonParameterised_proto_goTypes,
		DependencyIndexes: file_waCommonParameterised_WACommonParameterised_proto_depIdxs,
		EnumInfos:         file_waCommonParameterised_WACommonParameterised_proto_enumTypes,
		MessageInfos:      file_waCommonParameterised_WACommonParameterised_proto_msgTypes,
	}.Build()
	File_waCommonParameterised_WACommonParameterised_proto = out.File
	file_waCommonParameterised_WACommonParameterised_proto_rawDesc = nil
	file_waCommonParameterised_WACommonParameterised_proto_goTypes = nil
	file_waCommonParameterised_WACommonParameterised_proto_depIdxs = nil
}
