// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: instamadilloCoreTypeText/InstamadilloCoreTypeText.proto

package instamadilloCoreTypeText

import (
	instamadilloCoreTypeMedia "go.mau.fi/whatsmeow/proto/instamadilloCoreTypeMedia"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Text_FormatStyle int32

const (
	Text_TEXT_FORMAT_STYLE_UNSPECIFIED   Text_FormatStyle = 0
	Text_TEXT_FORMAT_STYLE_BOLD          Text_FormatStyle = 1
	Text_TEXT_FORMAT_STYLE_ITALIC        Text_FormatStyle = 2
	Text_TEXT_FORMAT_STYLE_STRIKETHROUGH Text_FormatStyle = 3
	Text_TEXT_FORMAT_STYLE_UNDERLINE     Text_FormatStyle = 4
	Text_TEXT_FORMAT_STYLE_INVALID       Text_FormatStyle = 5
)

// Enum value maps for Text_FormatStyle.
var (
	Text_FormatStyle_name = map[int32]string{
		0: "TEXT_FORMAT_STYLE_UNSPECIFIED",
		1: "TEXT_FORMAT_STYLE_BOLD",
		2: "TEXT_FORMAT_STYLE_ITALIC",
		3: "TEXT_FORMAT_STYLE_STRIKETHROUGH",
		4: "TEXT_FORMAT_STYLE_UNDERLINE",
		5: "TEXT_FORMAT_STYLE_INVALID",
	}
	Text_FormatStyle_value = map[string]int32{
		"TEXT_FORMAT_STYLE_UNSPECIFIED":   0,
		"TEXT_FORMAT_STYLE_BOLD":          1,
		"TEXT_FORMAT_STYLE_ITALIC":        2,
		"TEXT_FORMAT_STYLE_STRIKETHROUGH": 3,
		"TEXT_FORMAT_STYLE_UNDERLINE":     4,
		"TEXT_FORMAT_STYLE_INVALID":       5,
	}
)

func (x Text_FormatStyle) Enum() *Text_FormatStyle {
	p := new(Text_FormatStyle)
	*p = x
	return p
}

func (x Text_FormatStyle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Text_FormatStyle) Descriptor() protoreflect.EnumDescriptor {
	return file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_enumTypes[0].Descriptor()
}

func (Text_FormatStyle) Type() protoreflect.EnumType {
	return &file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_enumTypes[0]
}

func (x Text_FormatStyle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Text_FormatStyle) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Text_FormatStyle(num)
	return nil
}

// Deprecated: Use Text_FormatStyle.Descriptor instead.
func (Text_FormatStyle) EnumDescriptor() ([]byte, []int) {
	return file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_rawDescGZIP(), []int{0, 0}
}

type Text struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text                         *string                        `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	IsSuggestedReply             *bool                          `protobuf:"varint,2,opt,name=isSuggestedReply" json:"isSuggestedReply,omitempty"`
	PostbackPayload              *string                        `protobuf:"bytes,3,opt,name=postbackPayload" json:"postbackPayload,omitempty"`
	PowerUpData                  *PowerUpsData                  `protobuf:"bytes,4,opt,name=powerUpData" json:"powerUpData,omitempty"`
	Commands                     []*CommandRangeData            `protobuf:"bytes,5,rep,name=commands" json:"commands,omitempty"`
	AnimatedEmojiCharacterRanges []*AnimatedEmojiCharacterRange `protobuf:"bytes,6,rep,name=animatedEmojiCharacterRanges" json:"animatedEmojiCharacterRanges,omitempty"`
}

func (x *Text) Reset() {
	*x = Text{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_rawDescGZIP(), []int{0}
}

func (x *Text) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *Text) GetIsSuggestedReply() bool {
	if x != nil && x.IsSuggestedReply != nil {
		return *x.IsSuggestedReply
	}
	return false
}

func (x *Text) GetPostbackPayload() string {
	if x != nil && x.PostbackPayload != nil {
		return *x.PostbackPayload
	}
	return ""
}

func (x *Text) GetPowerUpData() *PowerUpsData {
	if x != nil {
		return x.PowerUpData
	}
	return nil
}

func (x *Text) GetCommands() []*CommandRangeData {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *Text) GetAnimatedEmojiCharacterRanges() []*AnimatedEmojiCharacterRange {
	if x != nil {
		return x.AnimatedEmojiCharacterRanges
	}
	return nil
}

type PowerUpsData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Style           *int32                                          `protobuf:"varint,1,opt,name=style" json:"style,omitempty"`
	MediaAttachment *instamadilloCoreTypeMedia.CommonMediaTransport `protobuf:"bytes,2,opt,name=mediaAttachment" json:"mediaAttachment,omitempty"`
}

func (x *PowerUpsData) Reset() {
	*x = PowerUpsData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PowerUpsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerUpsData) ProtoMessage() {}

func (x *PowerUpsData) ProtoReflect() protoreflect.Message {
	mi := &file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerUpsData.ProtoReflect.Descriptor instead.
func (*PowerUpsData) Descriptor() ([]byte, []int) {
	return file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_rawDescGZIP(), []int{1}
}

func (x *PowerUpsData) GetStyle() int32 {
	if x != nil && x.Style != nil {
		return *x.Style
	}
	return 0
}

func (x *PowerUpsData) GetMediaAttachment() *instamadilloCoreTypeMedia.CommonMediaTransport {
	if x != nil {
		return x.MediaAttachment
	}
	return nil
}

type CommandRangeData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset           *int32  `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Length           *int32  `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	Type             *int32  `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	FBID             *string `protobuf:"bytes,4,opt,name=FBID" json:"FBID,omitempty"`
	UserOrThreadFbid *string `protobuf:"bytes,5,opt,name=userOrThreadFbid" json:"userOrThreadFbid,omitempty"`
}

func (x *CommandRangeData) Reset() {
	*x = CommandRangeData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandRangeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRangeData) ProtoMessage() {}

func (x *CommandRangeData) ProtoReflect() protoreflect.Message {
	mi := &file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRangeData.ProtoReflect.Descriptor instead.
func (*CommandRangeData) Descriptor() ([]byte, []int) {
	return file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_rawDescGZIP(), []int{2}
}

func (x *CommandRangeData) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *CommandRangeData) GetLength() int32 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

func (x *CommandRangeData) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *CommandRangeData) GetFBID() string {
	if x != nil && x.FBID != nil {
		return *x.FBID
	}
	return ""
}

func (x *CommandRangeData) GetUserOrThreadFbid() string {
	if x != nil && x.UserOrThreadFbid != nil {
		return *x.UserOrThreadFbid
	}
	return ""
}

type FormattedText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset *int32            `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Length *int32            `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	Style  *Text_FormatStyle `protobuf:"varint,3,opt,name=style,enum=InstamadilloCoreTypeText.Text_FormatStyle" json:"style,omitempty"`
}

func (x *FormattedText) Reset() {
	*x = FormattedText{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormattedText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormattedText) ProtoMessage() {}

func (x *FormattedText) ProtoReflect() protoreflect.Message {
	mi := &file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormattedText.ProtoReflect.Descriptor instead.
func (*FormattedText) Descriptor() ([]byte, []int) {
	return file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_rawDescGZIP(), []int{3}
}

func (x *FormattedText) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *FormattedText) GetLength() int32 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

func (x *FormattedText) GetStyle() Text_FormatStyle {
	if x != nil && x.Style != nil {
		return *x.Style
	}
	return Text_TEXT_FORMAT_STYLE_UNSPECIFIED
}

type AnimatedEmojiCharacterRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset *int32 `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Length *int32 `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
}

func (x *AnimatedEmojiCharacterRange) Reset() {
	*x = AnimatedEmojiCharacterRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnimatedEmojiCharacterRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimatedEmojiCharacterRange) ProtoMessage() {}

func (x *AnimatedEmojiCharacterRange) ProtoReflect() protoreflect.Message {
	mi := &file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimatedEmojiCharacterRange.ProtoReflect.Descriptor instead.
func (*AnimatedEmojiCharacterRange) Descriptor() ([]byte, []int) {
	return file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_rawDescGZIP(), []int{4}
}

func (x *AnimatedEmojiCharacterRange) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *AnimatedEmojiCharacterRange) GetLength() int32 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

var File_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto protoreflect.FileDescriptor

var file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_rawDesc = []byte{
	0x0a, 0x37, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x43, 0x6f,
	0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x54, 0x65, 0x78, 0x74, 0x2f, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x43, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x54,
	0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x43, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x54,
	0x65, 0x78, 0x74, 0x1a, 0x39, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c,
	0x6f, 0x43, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x2f, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x43, 0x6f, 0x72, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcf,
	0x04, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x2a, 0x0a, 0x10, 0x69,
	0x73, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x69, 0x73, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x0f, 0x70, 0x6f, 0x73, 0x74, 0x62,
	0x61, 0x63, 0x6b, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x70, 0x6f, 0x73, 0x74, 0x62, 0x61, 0x63, 0x6b, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x48, 0x0a, 0x0b, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x55, 0x70, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6d, 0x61,
	0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x43, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x54, 0x65, 0x78,
	0x74, 0x2e, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x55, 0x70, 0x73, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0b,
	0x70, 0x6f, 0x77, 0x65, 0x72, 0x55, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x46, 0x0a, 0x08, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x43, 0x6f, 0x72, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x54, 0x65, 0x78, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x73, 0x12, 0x79, 0x0a, 0x1c, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x45,
	0x6d, 0x6f, 0x6a, 0x69, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x43, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x54, 0x65, 0x78, 0x74, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x45, 0x6d, 0x6f,
	0x6a, 0x69, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x1c, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x22, 0xcf,
	0x01, 0x0a, 0x0b, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x12, 0x21,
	0x0a, 0x1d, 0x54, 0x45, 0x58, 0x54, 0x5f, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x5f, 0x53, 0x54,
	0x59, 0x4c, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x1a, 0x0a, 0x16, 0x54, 0x45, 0x58, 0x54, 0x5f, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54,
	0x5f, 0x53, 0x54, 0x59, 0x4c, 0x45, 0x5f, 0x42, 0x4f, 0x4c, 0x44, 0x10, 0x01, 0x12, 0x1c, 0x0a,
	0x18, 0x54, 0x45, 0x58, 0x54, 0x5f, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x5f, 0x53, 0x54, 0x59,
	0x4c, 0x45, 0x5f, 0x49, 0x54, 0x41, 0x4c, 0x49, 0x43, 0x10, 0x02, 0x12, 0x23, 0x0a, 0x1f, 0x54,
	0x45, 0x58, 0x54, 0x5f, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x5f, 0x53, 0x54, 0x59, 0x4c, 0x45,
	0x5f, 0x53, 0x54, 0x52, 0x49, 0x4b, 0x45, 0x54, 0x48, 0x52, 0x4f, 0x55, 0x47, 0x48, 0x10, 0x03,
	0x12, 0x1f, 0x0a, 0x1b, 0x54, 0x45, 0x58, 0x54, 0x5f, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x5f,
	0x53, 0x54, 0x59, 0x4c, 0x45, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x52, 0x4c, 0x49, 0x4e, 0x45, 0x10,
	0x04, 0x12, 0x1d, 0x0a, 0x19, 0x54, 0x45, 0x58, 0x54, 0x5f, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54,
	0x5f, 0x53, 0x54, 0x59, 0x4c, 0x45, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x05,
	0x22, 0x7f, 0x0a, 0x0c, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x55, 0x70, 0x73, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x12, 0x59, 0x0a, 0x0f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x41,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2f, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x43, 0x6f,
	0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74,
	0x52, 0x0f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e,
	0x74, 0x22, 0x96, 0x01, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x42,
	0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x42, 0x49, 0x44, 0x12, 0x2a,
	0x0a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x46, 0x62,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x75, 0x73, 0x65, 0x72, 0x4f, 0x72,
	0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x46, 0x62, 0x69, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x0d, 0x46,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x64, 0x54, 0x65, 0x78, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x40, 0x0a, 0x05,
	0x73, 0x74, 0x79, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x43, 0x6f, 0x72, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x54, 0x65, 0x78, 0x74, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x2e, 0x46, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x52, 0x05, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x22, 0x4d,
	0x0a, 0x1b, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x42, 0x34, 0x5a,
	0x32, 0x67, 0x6f, 0x2e, 0x6d, 0x61, 0x75, 0x2e, 0x66, 0x69, 0x2f, 0x77, 0x68, 0x61, 0x74, 0x73,
	0x6d, 0x65, 0x6f, 0x77, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x43, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x54,
	0x65, 0x78, 0x74,
}

var (
	file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_rawDescOnce sync.Once
	file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_rawDescData = file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_rawDesc
)

func file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_rawDescGZIP() []byte {
	file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_rawDescOnce.Do(func() {
		file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_rawDescData = protoimpl.X.CompressGZIP(file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_rawDescData)
	})
	return file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_rawDescData
}

var file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_goTypes = []interface{}{
	(Text_FormatStyle)(0),               // 0: InstamadilloCoreTypeText.Text.FormatStyle
	(*Text)(nil),                        // 1: InstamadilloCoreTypeText.Text
	(*PowerUpsData)(nil),                // 2: InstamadilloCoreTypeText.PowerUpsData
	(*CommandRangeData)(nil),            // 3: InstamadilloCoreTypeText.CommandRangeData
	(*FormattedText)(nil),               // 4: InstamadilloCoreTypeText.FormattedText
	(*AnimatedEmojiCharacterRange)(nil), // 5: InstamadilloCoreTypeText.AnimatedEmojiCharacterRange
	(*instamadilloCoreTypeMedia.CommonMediaTransport)(nil), // 6: InstamadilloCoreTypeMedia.CommonMediaTransport
}
var file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_depIdxs = []int32{
	2, // 0: InstamadilloCoreTypeText.Text.powerUpData:type_name -> InstamadilloCoreTypeText.PowerUpsData
	3, // 1: InstamadilloCoreTypeText.Text.commands:type_name -> InstamadilloCoreTypeText.CommandRangeData
	5, // 2: InstamadilloCoreTypeText.Text.animatedEmojiCharacterRanges:type_name -> InstamadilloCoreTypeText.AnimatedEmojiCharacterRange
	6, // 3: InstamadilloCoreTypeText.PowerUpsData.mediaAttachment:type_name -> InstamadilloCoreTypeMedia.CommonMediaTransport
	0, // 4: InstamadilloCoreTypeText.FormattedText.style:type_name -> InstamadilloCoreTypeText.Text.FormatStyle
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_init() }
func file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_init() {
	if File_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Text); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PowerUpsData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandRangeData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormattedText); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnimatedEmojiCharacterRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_goTypes,
		DependencyIndexes: file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_depIdxs,
		EnumInfos:         file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_enumTypes,
		MessageInfos:      file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_msgTypes,
	}.Build()
	File_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto = out.File
	file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_rawDesc = nil
	file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_goTypes = nil
	file_instamadilloCoreTypeText_InstamadilloCoreTypeText_proto_depIdxs = nil
}
