// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: instamadilloSupplementMessage/InstamadilloSupplementMessage.proto

package instamadilloSupplementMessage

import (
	instamadilloCoreTypeMedia "github.com/song-xiang13/whatsmeow/proto/instamadilloCoreTypeMedia"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SupplementMessagePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetMessageOtid              *string                   `protobuf:"bytes,1,opt,name=targetMessageOtid" json:"targetMessageOtid,omitempty"`
	UniquingKeyForSupplementalData *string                   `protobuf:"bytes,2,opt,name=uniquingKeyForSupplementalData" json:"uniquingKeyForSupplementalData,omitempty"`
	Content                        *SupplementMessageContent `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	TargetMessageWaServerTimeSec   *string                   `protobuf:"bytes,4,opt,name=targetMessageWaServerTimeSec" json:"targetMessageWaServerTimeSec,omitempty"`
	TargetWaThreadID               *string                   `protobuf:"bytes,5,opt,name=targetWaThreadID" json:"targetWaThreadID,omitempty"`
}

func (x *SupplementMessagePayload) Reset() {
	*x = SupplementMessagePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupplementMessagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplementMessagePayload) ProtoMessage() {}

func (x *SupplementMessagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplementMessagePayload.ProtoReflect.Descriptor instead.
func (*SupplementMessagePayload) Descriptor() ([]byte, []int) {
	return file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_rawDescGZIP(), []int{0}
}

func (x *SupplementMessagePayload) GetTargetMessageOtid() string {
	if x != nil && x.TargetMessageOtid != nil {
		return *x.TargetMessageOtid
	}
	return ""
}

func (x *SupplementMessagePayload) GetUniquingKeyForSupplementalData() string {
	if x != nil && x.UniquingKeyForSupplementalData != nil {
		return *x.UniquingKeyForSupplementalData
	}
	return ""
}

func (x *SupplementMessagePayload) GetContent() *SupplementMessageContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SupplementMessagePayload) GetTargetMessageWaServerTimeSec() string {
	if x != nil && x.TargetMessageWaServerTimeSec != nil {
		return *x.TargetMessageWaServerTimeSec
	}
	return ""
}

func (x *SupplementMessagePayload) GetTargetWaThreadID() string {
	if x != nil && x.TargetWaThreadID != nil {
		return *x.TargetWaThreadID
	}
	return ""
}

type SupplementMessageContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to SupplementMessageContent:
	//
	//	*SupplementMessageContent_Reaction
	//	*SupplementMessageContent_ContentView
	//	*SupplementMessageContent_EditText
	//	*SupplementMessageContent_MediaReaction
	//	*SupplementMessageContent_OriginalTransportPayload
	//	*SupplementMessageContent_MediaInterventions
	SupplementMessageContent isSupplementMessageContent_SupplementMessageContent `protobuf_oneof:"supplementMessageContent"`
}

func (x *SupplementMessageContent) Reset() {
	*x = SupplementMessageContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupplementMessageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplementMessageContent) ProtoMessage() {}

func (x *SupplementMessageContent) ProtoReflect() protoreflect.Message {
	mi := &file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplementMessageContent.ProtoReflect.Descriptor instead.
func (*SupplementMessageContent) Descriptor() ([]byte, []int) {
	return file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_rawDescGZIP(), []int{1}
}

func (m *SupplementMessageContent) GetSupplementMessageContent() isSupplementMessageContent_SupplementMessageContent {
	if m != nil {
		return m.SupplementMessageContent
	}
	return nil
}

func (x *SupplementMessageContent) GetReaction() *Reaction {
	if x, ok := x.GetSupplementMessageContent().(*SupplementMessageContent_Reaction); ok {
		return x.Reaction
	}
	return nil
}

func (x *SupplementMessageContent) GetContentView() *ContentView {
	if x, ok := x.GetSupplementMessageContent().(*SupplementMessageContent_ContentView); ok {
		return x.ContentView
	}
	return nil
}

func (x *SupplementMessageContent) GetEditText() *EditText {
	if x, ok := x.GetSupplementMessageContent().(*SupplementMessageContent_EditText); ok {
		return x.EditText
	}
	return nil
}

func (x *SupplementMessageContent) GetMediaReaction() *MediaReaction {
	if x, ok := x.GetSupplementMessageContent().(*SupplementMessageContent_MediaReaction); ok {
		return x.MediaReaction
	}
	return nil
}

func (x *SupplementMessageContent) GetOriginalTransportPayload() *OriginalTransportPayload {
	if x, ok := x.GetSupplementMessageContent().(*SupplementMessageContent_OriginalTransportPayload); ok {
		return x.OriginalTransportPayload
	}
	return nil
}

func (x *SupplementMessageContent) GetMediaInterventions() *MediaInterventions {
	if x, ok := x.GetSupplementMessageContent().(*SupplementMessageContent_MediaInterventions); ok {
		return x.MediaInterventions
	}
	return nil
}

type isSupplementMessageContent_SupplementMessageContent interface {
	isSupplementMessageContent_SupplementMessageContent()
}

type SupplementMessageContent_Reaction struct {
	Reaction *Reaction `protobuf:"bytes,1,opt,name=reaction,oneof"`
}

type SupplementMessageContent_ContentView struct {
	ContentView *ContentView `protobuf:"bytes,2,opt,name=contentView,oneof"`
}

type SupplementMessageContent_EditText struct {
	EditText *EditText `protobuf:"bytes,3,opt,name=editText,oneof"`
}

type SupplementMessageContent_MediaReaction struct {
	MediaReaction *MediaReaction `protobuf:"bytes,4,opt,name=mediaReaction,oneof"`
}

type SupplementMessageContent_OriginalTransportPayload struct {
	OriginalTransportPayload *OriginalTransportPayload `protobuf:"bytes,5,opt,name=originalTransportPayload,oneof"`
}

type SupplementMessageContent_MediaInterventions struct {
	MediaInterventions *MediaInterventions `protobuf:"bytes,6,opt,name=mediaInterventions,oneof"`
}

func (*SupplementMessageContent_Reaction) isSupplementMessageContent_SupplementMessageContent() {}

func (*SupplementMessageContent_ContentView) isSupplementMessageContent_SupplementMessageContent() {}

func (*SupplementMessageContent_EditText) isSupplementMessageContent_SupplementMessageContent() {}

func (*SupplementMessageContent_MediaReaction) isSupplementMessageContent_SupplementMessageContent() {
}

func (*SupplementMessageContent_OriginalTransportPayload) isSupplementMessageContent_SupplementMessageContent() {
}

func (*SupplementMessageContent_MediaInterventions) isSupplementMessageContent_SupplementMessageContent() {
}

type MediaReaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MediaID  *string   `protobuf:"bytes,1,opt,name=mediaID" json:"mediaID,omitempty"`
	Reaction *Reaction `protobuf:"bytes,2,opt,name=reaction" json:"reaction,omitempty"`
}

func (x *MediaReaction) Reset() {
	*x = MediaReaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaReaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaReaction) ProtoMessage() {}

func (x *MediaReaction) ProtoReflect() protoreflect.Message {
	mi := &file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaReaction.ProtoReflect.Descriptor instead.
func (*MediaReaction) Descriptor() ([]byte, []int) {
	return file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_rawDescGZIP(), []int{2}
}

func (x *MediaReaction) GetMediaID() string {
	if x != nil && x.MediaID != nil {
		return *x.MediaID
	}
	return ""
}

func (x *MediaReaction) GetReaction() *Reaction {
	if x != nil {
		return x.Reaction
	}
	return nil
}

type Reaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReactionType   *string `protobuf:"bytes,1,opt,name=reactionType" json:"reactionType,omitempty"`
	ReactionStatus *string `protobuf:"bytes,2,opt,name=reactionStatus" json:"reactionStatus,omitempty"`
	Emoji          *string `protobuf:"bytes,3,opt,name=emoji" json:"emoji,omitempty"`
	SuperReactType *string `protobuf:"bytes,4,opt,name=superReactType" json:"superReactType,omitempty"`
	ActionLogOtid  *string `protobuf:"bytes,5,opt,name=actionLogOtid" json:"actionLogOtid,omitempty"`
}

func (x *Reaction) Reset() {
	*x = Reaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reaction) ProtoMessage() {}

func (x *Reaction) ProtoReflect() protoreflect.Message {
	mi := &file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reaction.ProtoReflect.Descriptor instead.
func (*Reaction) Descriptor() ([]byte, []int) {
	return file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_rawDescGZIP(), []int{3}
}

func (x *Reaction) GetReactionType() string {
	if x != nil && x.ReactionType != nil {
		return *x.ReactionType
	}
	return ""
}

func (x *Reaction) GetReactionStatus() string {
	if x != nil && x.ReactionStatus != nil {
		return *x.ReactionStatus
	}
	return ""
}

func (x *Reaction) GetEmoji() string {
	if x != nil && x.Emoji != nil {
		return *x.Emoji
	}
	return ""
}

func (x *Reaction) GetSuperReactType() string {
	if x != nil && x.SuperReactType != nil {
		return *x.SuperReactType
	}
	return ""
}

func (x *Reaction) GetActionLogOtid() string {
	if x != nil && x.ActionLogOtid != nil {
		return *x.ActionLogOtid
	}
	return ""
}

type ContentView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seen          *bool   `protobuf:"varint,1,opt,name=seen" json:"seen,omitempty"`
	Screenshotted *bool   `protobuf:"varint,2,opt,name=screenshotted" json:"screenshotted,omitempty"`
	Replayed      *bool   `protobuf:"varint,3,opt,name=replayed" json:"replayed,omitempty"`
	Mimetype      *string `protobuf:"bytes,4,opt,name=mimetype" json:"mimetype,omitempty"`
	ObjectID      *string `protobuf:"bytes,5,opt,name=objectID" json:"objectID,omitempty"`
}

func (x *ContentView) Reset() {
	*x = ContentView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContentView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentView) ProtoMessage() {}

func (x *ContentView) ProtoReflect() protoreflect.Message {
	mi := &file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentView.ProtoReflect.Descriptor instead.
func (*ContentView) Descriptor() ([]byte, []int) {
	return file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_rawDescGZIP(), []int{4}
}

func (x *ContentView) GetSeen() bool {
	if x != nil && x.Seen != nil {
		return *x.Seen
	}
	return false
}

func (x *ContentView) GetScreenshotted() bool {
	if x != nil && x.Screenshotted != nil {
		return *x.Screenshotted
	}
	return false
}

func (x *ContentView) GetReplayed() bool {
	if x != nil && x.Replayed != nil {
		return *x.Replayed
	}
	return false
}

func (x *ContentView) GetMimetype() string {
	if x != nil && x.Mimetype != nil {
		return *x.Mimetype
	}
	return ""
}

func (x *ContentView) GetObjectID() string {
	if x != nil && x.ObjectID != nil {
		return *x.ObjectID
	}
	return ""
}

type EditText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewContent *string `protobuf:"bytes,1,opt,name=newContent" json:"newContent,omitempty"`
	EditCount  *int32  `protobuf:"varint,2,opt,name=editCount" json:"editCount,omitempty"`
}

func (x *EditText) Reset() {
	*x = EditText{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditText) ProtoMessage() {}

func (x *EditText) ProtoReflect() protoreflect.Message {
	mi := &file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditText.ProtoReflect.Descriptor instead.
func (*EditText) Descriptor() ([]byte, []int) {
	return file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_rawDescGZIP(), []int{5}
}

func (x *EditText) GetNewContent() string {
	if x != nil && x.NewContent != nil {
		return *x.NewContent
	}
	return ""
}

func (x *EditText) GetEditCount() int32 {
	if x != nil && x.EditCount != nil {
		return *x.EditCount
	}
	return 0
}

type OriginalTransportPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginalTransportPayload []byte `protobuf:"bytes,1,opt,name=originalTransportPayload" json:"originalTransportPayload,omitempty"`
}

func (x *OriginalTransportPayload) Reset() {
	*x = OriginalTransportPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OriginalTransportPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OriginalTransportPayload) ProtoMessage() {}

func (x *OriginalTransportPayload) ProtoReflect() protoreflect.Message {
	mi := &file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OriginalTransportPayload.ProtoReflect.Descriptor instead.
func (*OriginalTransportPayload) Descriptor() ([]byte, []int) {
	return file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_rawDescGZIP(), []int{6}
}

func (x *OriginalTransportPayload) GetOriginalTransportPayload() []byte {
	if x != nil {
		return x.OriginalTransportPayload
	}
	return nil
}

type MediaInterventions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MediaID          *string                                           `protobuf:"bytes,1,opt,name=mediaID" json:"mediaID,omitempty"`
	InterventionType *instamadilloCoreTypeMedia.Media_InterventionType `protobuf:"varint,2,opt,name=interventionType,enum=InstamadilloCoreTypeMedia.Media_InterventionType" json:"interventionType,omitempty"`
}

func (x *MediaInterventions) Reset() {
	*x = MediaInterventions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaInterventions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaInterventions) ProtoMessage() {}

func (x *MediaInterventions) ProtoReflect() protoreflect.Message {
	mi := &file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaInterventions.ProtoReflect.Descriptor instead.
func (*MediaInterventions) Descriptor() ([]byte, []int) {
	return file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_rawDescGZIP(), []int{7}
}

func (x *MediaInterventions) GetMediaID() string {
	if x != nil && x.MediaID != nil {
		return *x.MediaID
	}
	return ""
}

func (x *MediaInterventions) GetInterventionType() instamadilloCoreTypeMedia.Media_InterventionType {
	if x != nil && x.InterventionType != nil {
		return *x.InterventionType
	}
	return instamadilloCoreTypeMedia.Media_InterventionType(0)
}

var File_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto protoreflect.FileDescriptor

var file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_rawDesc = []byte{
	0x0a, 0x41, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x53, 0x75,
	0x70, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x53, 0x75, 0x70, 0x70,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c,
	0x6f, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x1a, 0x39, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f,
	0x43, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x2f, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x43, 0x6f, 0x72, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd3, 0x02,
	0x0a, 0x18, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x74, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x4f, 0x74, 0x69, 0x64, 0x12, 0x46, 0x0a, 0x1e, 0x75, 0x6e, 0x69, 0x71,
	0x75, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x46, 0x6f, 0x72, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x1e, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x46, 0x6f, 0x72,
	0x53, 0x75, 0x70, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x51, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x37, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f,
	0x53, 0x75, 0x70, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x42, 0x0a, 0x1c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x57, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65,
	0x53, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x1c, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x54, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63, 0x12, 0x2a, 0x0a, 0x10, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x57, 0x61, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x57, 0x61, 0x54, 0x68, 0x72, 0x65, 0x61,
	0x64, 0x49, 0x44, 0x22, 0xc6, 0x04, 0x0a, 0x18, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x45, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x27, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c,
	0x6f, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x08, 0x72,
	0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4e, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x56, 0x69, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x53, 0x75, 0x70, 0x70, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x56, 0x69, 0x65, 0x77, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x56, 0x69, 0x65, 0x77, 0x12, 0x45, 0x0a, 0x08, 0x65, 0x64, 0x69, 0x74, 0x54,
	0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x54, 0x65,
	0x78, 0x74, 0x48, 0x00, 0x52, 0x08, 0x65, 0x64, 0x69, 0x74, 0x54, 0x65, 0x78, 0x74, 0x12, 0x54,
	0x0a, 0x0d, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6d, 0x61, 0x64,
	0x69, 0x6c, 0x6c, 0x6f, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0d, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x75, 0x0a, 0x18, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6d, 0x61,
	0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48,
	0x00, 0x52, 0x18, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x63, 0x0a, 0x12, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6d,
	0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x48, 0x00, 0x52, 0x12, 0x6d, 0x65,
	0x64, 0x69, 0x61, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x42, 0x1a, 0x0a, 0x18, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x6e, 0x0a, 0x0d,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x49, 0x44, 0x12, 0x43, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x08, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xba, 0x01, 0x0a,
	0x08, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a,
	0x0e, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x12, 0x26, 0x0a, 0x0e, 0x73,
	0x75, 0x70, 0x65, 0x72, 0x52, 0x65, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x75, 0x70, 0x65, 0x72, 0x52, 0x65, 0x61, 0x63, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x67,
	0x4f, 0x74, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x4c, 0x6f, 0x67, 0x4f, 0x74, 0x69, 0x64, 0x22, 0x9b, 0x01, 0x0a, 0x0b, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x56, 0x69, 0x65, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x73, 0x65, 0x65, 0x6e, 0x12, 0x24, 0x0a,
	0x0d, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74, 0x74, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74,
	0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x6d, 0x69, 0x6d, 0x65, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6d, 0x69, 0x6d, 0x65, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x22, 0x48, 0x0a, 0x08, 0x45, 0x64, 0x69, 0x74, 0x54,
	0x65, 0x78, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x65, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x64, 0x69, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x64, 0x69, 0x74, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x56, 0x0a, 0x18, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x3a, 0x0a,
	0x18, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x18, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x8d, 0x01, 0x0a, 0x12, 0x4d, 0x65,
	0x64, 0x69, 0x61, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x49, 0x44, 0x12, 0x5d, 0x0a, 0x10, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6d, 0x61, 0x64, 0x69,
	0x6c, 0x6c, 0x6f, 0x43, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x65, 0x6e, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x10, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x65,
	0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x6f, 0x2e,
	0x6d, 0x61, 0x75, 0x2e, 0x66, 0x69, 0x2f, 0x77, 0x68, 0x61, 0x74, 0x73, 0x6d, 0x65, 0x6f, 0x77,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6d, 0x61, 0x64, 0x69,
	0x6c, 0x6c, 0x6f, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65,
}

var (
	file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_rawDescOnce sync.Once
	file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_rawDescData = file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_rawDesc
)

func file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_rawDescGZIP() []byte {
	file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_rawDescOnce.Do(func() {
		file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_rawDescData)
	})
	return file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_rawDescData
}

var file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_goTypes = []interface{}{
	(*SupplementMessagePayload)(nil),                      // 0: InstamadilloSupplementMessage.SupplementMessagePayload
	(*SupplementMessageContent)(nil),                      // 1: InstamadilloSupplementMessage.SupplementMessageContent
	(*MediaReaction)(nil),                                 // 2: InstamadilloSupplementMessage.MediaReaction
	(*Reaction)(nil),                                      // 3: InstamadilloSupplementMessage.Reaction
	(*ContentView)(nil),                                   // 4: InstamadilloSupplementMessage.ContentView
	(*EditText)(nil),                                      // 5: InstamadilloSupplementMessage.EditText
	(*OriginalTransportPayload)(nil),                      // 6: InstamadilloSupplementMessage.OriginalTransportPayload
	(*MediaInterventions)(nil),                            // 7: InstamadilloSupplementMessage.MediaInterventions
	(instamadilloCoreTypeMedia.Media_InterventionType)(0), // 8: InstamadilloCoreTypeMedia.Media.InterventionType
}
var file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_depIdxs = []int32{
	1, // 0: InstamadilloSupplementMessage.SupplementMessagePayload.content:type_name -> InstamadilloSupplementMessage.SupplementMessageContent
	3, // 1: InstamadilloSupplementMessage.SupplementMessageContent.reaction:type_name -> InstamadilloSupplementMessage.Reaction
	4, // 2: InstamadilloSupplementMessage.SupplementMessageContent.contentView:type_name -> InstamadilloSupplementMessage.ContentView
	5, // 3: InstamadilloSupplementMessage.SupplementMessageContent.editText:type_name -> InstamadilloSupplementMessage.EditText
	2, // 4: InstamadilloSupplementMessage.SupplementMessageContent.mediaReaction:type_name -> InstamadilloSupplementMessage.MediaReaction
	6, // 5: InstamadilloSupplementMessage.SupplementMessageContent.originalTransportPayload:type_name -> InstamadilloSupplementMessage.OriginalTransportPayload
	7, // 6: InstamadilloSupplementMessage.SupplementMessageContent.mediaInterventions:type_name -> InstamadilloSupplementMessage.MediaInterventions
	3, // 7: InstamadilloSupplementMessage.MediaReaction.reaction:type_name -> InstamadilloSupplementMessage.Reaction
	8, // 8: InstamadilloSupplementMessage.MediaInterventions.interventionType:type_name -> InstamadilloCoreTypeMedia.Media.InterventionType
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_init() }
func file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_init() {
	if File_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupplementMessagePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupplementMessageContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaReaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContentView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditText); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OriginalTransportPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaInterventions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*SupplementMessageContent_Reaction)(nil),
		(*SupplementMessageContent_ContentView)(nil),
		(*SupplementMessageContent_EditText)(nil),
		(*SupplementMessageContent_MediaReaction)(nil),
		(*SupplementMessageContent_OriginalTransportPayload)(nil),
		(*SupplementMessageContent_MediaInterventions)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_goTypes,
		DependencyIndexes: file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_depIdxs,
		MessageInfos:      file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_msgTypes,
	}.Build()
	File_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto = out.File
	file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_rawDesc = nil
	file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_goTypes = nil
	file_instamadilloSupplementMessage_InstamadilloSupplementMessage_proto_depIdxs = nil
}
