// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: waSyncdSnapshotRecovery/WAWebProtobufsSyncdSnapshotRecovery.proto

package waSyncdSnapshotRecovery

import (
	waSyncAction "github.com/song-xiang13/whatsmeow/proto/waSyncAction"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncdSnapshotRecovery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version          *SyncdVersion           `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	CollectionName   *string                 `protobuf:"bytes,2,opt,name=collectionName" json:"collectionName,omitempty"`
	MutationRecords  []*SyncdPlainTextRecord `protobuf:"bytes,3,rep,name=mutationRecords" json:"mutationRecords,omitempty"`
	CollectionLthash []byte                  `protobuf:"bytes,4,opt,name=collectionLthash" json:"collectionLthash,omitempty"`
}

func (x *SyncdSnapshotRecovery) Reset() {
	*x = SyncdSnapshotRecovery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncdSnapshotRecovery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncdSnapshotRecovery) ProtoMessage() {}

func (x *SyncdSnapshotRecovery) ProtoReflect() protoreflect.Message {
	mi := &file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncdSnapshotRecovery.ProtoReflect.Descriptor instead.
func (*SyncdSnapshotRecovery) Descriptor() ([]byte, []int) {
	return file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_rawDescGZIP(), []int{0}
}

func (x *SyncdSnapshotRecovery) GetVersion() *SyncdVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *SyncdSnapshotRecovery) GetCollectionName() string {
	if x != nil && x.CollectionName != nil {
		return *x.CollectionName
	}
	return ""
}

func (x *SyncdSnapshotRecovery) GetMutationRecords() []*SyncdPlainTextRecord {
	if x != nil {
		return x.MutationRecords
	}
	return nil
}

func (x *SyncdSnapshotRecovery) GetCollectionLthash() []byte {
	if x != nil {
		return x.CollectionLthash
	}
	return nil
}

type SyncdPlainTextRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *waSyncAction.SyncActionData `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	KeyID []byte                       `protobuf:"bytes,2,opt,name=keyID" json:"keyID,omitempty"`
	Mac   []byte                       `protobuf:"bytes,3,opt,name=mac" json:"mac,omitempty"`
}

func (x *SyncdPlainTextRecord) Reset() {
	*x = SyncdPlainTextRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncdPlainTextRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncdPlainTextRecord) ProtoMessage() {}

func (x *SyncdPlainTextRecord) ProtoReflect() protoreflect.Message {
	mi := &file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncdPlainTextRecord.ProtoReflect.Descriptor instead.
func (*SyncdPlainTextRecord) Descriptor() ([]byte, []int) {
	return file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_rawDescGZIP(), []int{1}
}

func (x *SyncdPlainTextRecord) GetValue() *waSyncAction.SyncActionData {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SyncdPlainTextRecord) GetKeyID() []byte {
	if x != nil {
		return x.KeyID
	}
	return nil
}

func (x *SyncdPlainTextRecord) GetMac() []byte {
	if x != nil {
		return x.Mac
	}
	return nil
}

type SyncdVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version *uint64 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
}

func (x *SyncdVersion) Reset() {
	*x = SyncdVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncdVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncdVersion) ProtoMessage() {}

func (x *SyncdVersion) ProtoReflect() protoreflect.Message {
	mi := &file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncdVersion.ProtoReflect.Descriptor instead.
func (*SyncdVersion) Descriptor() ([]byte, []int) {
	return file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_rawDescGZIP(), []int{2}
}

func (x *SyncdVersion) GetVersion() uint64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

var File_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto protoreflect.FileDescriptor

var file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_rawDesc = []byte{
	0x0a, 0x41, 0x77, 0x61, 0x53, 0x79, 0x6e, 0x63, 0x64, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2f, 0x57, 0x41, 0x57, 0x65, 0x62, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x53, 0x79, 0x6e, 0x63, 0x64, 0x53, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x23, 0x57, 0x41, 0x57, 0x65, 0x62, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x73, 0x53, 0x79, 0x6e, 0x63, 0x64, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74,
	0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x1a, 0x2a, 0x77, 0x61, 0x53, 0x79, 0x6e, 0x63,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x57, 0x41, 0x57, 0x65, 0x62, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x53, 0x79, 0x6e, 0x63, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9d, 0x02, 0x0a, 0x15, 0x53, 0x79, 0x6e, 0x63, 0x64, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x12, 0x4b,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x31, 0x2e, 0x57, 0x41, 0x57, 0x65, 0x62, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73,
	0x53, 0x79, 0x6e, 0x63, 0x64, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x64, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x63, 0x0a, 0x0f, 0x6d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x57,
	0x41, 0x57, 0x65, 0x62, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x53, 0x79, 0x6e,
	0x63, 0x64, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x79, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x64, 0x50, 0x6c, 0x61, 0x69, 0x6e, 0x54, 0x65, 0x78,
	0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x0f, 0x6d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x74, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x10, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x74,
	0x68, 0x61, 0x73, 0x68, 0x22, 0x7d, 0x0a, 0x14, 0x53, 0x79, 0x6e, 0x63, 0x64, 0x50, 0x6c, 0x61,
	0x69, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x3d, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x57, 0x41,
	0x57, 0x65, 0x62, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x53, 0x79, 0x6e, 0x63, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6b,
	0x65, 0x79, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6b, 0x65, 0x79, 0x49,
	0x44, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6d, 0x61, 0x63, 0x22, 0x28, 0x0a, 0x0c, 0x53, 0x79, 0x6e, 0x63, 0x64, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x33, 0x5a,
	0x31, 0x67, 0x6f, 0x2e, 0x6d, 0x61, 0x75, 0x2e, 0x66, 0x69, 0x2f, 0x77, 0x68, 0x61, 0x74, 0x73,
	0x6d, 0x65, 0x6f, 0x77, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x53, 0x79, 0x6e,
	0x63, 0x64, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x79,
}

var (
	file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_rawDescOnce sync.Once
	file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_rawDescData = file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_rawDesc
)

func file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_rawDescGZIP() []byte {
	file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_rawDescOnce.Do(func() {
		file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_rawDescData = protoimpl.X.CompressGZIP(file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_rawDescData)
	})
	return file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_rawDescData
}

var file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_goTypes = []interface{}{
	(*SyncdSnapshotRecovery)(nil),       // 0: WAWebProtobufsSyncdSnapshotRecovery.SyncdSnapshotRecovery
	(*SyncdPlainTextRecord)(nil),        // 1: WAWebProtobufsSyncdSnapshotRecovery.SyncdPlainTextRecord
	(*SyncdVersion)(nil),                // 2: WAWebProtobufsSyncdSnapshotRecovery.SyncdVersion
	(*waSyncAction.SyncActionData)(nil), // 3: WAWebProtobufSyncAction.SyncActionData
}
var file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_depIdxs = []int32{
	2, // 0: WAWebProtobufsSyncdSnapshotRecovery.SyncdSnapshotRecovery.version:type_name -> WAWebProtobufsSyncdSnapshotRecovery.SyncdVersion
	1, // 1: WAWebProtobufsSyncdSnapshotRecovery.SyncdSnapshotRecovery.mutationRecords:type_name -> WAWebProtobufsSyncdSnapshotRecovery.SyncdPlainTextRecord
	3, // 2: WAWebProtobufsSyncdSnapshotRecovery.SyncdPlainTextRecord.value:type_name -> WAWebProtobufSyncAction.SyncActionData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_init() }
func file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_init() {
	if File_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncdSnapshotRecovery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncdPlainTextRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncdVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_goTypes,
		DependencyIndexes: file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_depIdxs,
		MessageInfos:      file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_msgTypes,
	}.Build()
	File_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto = out.File
	file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_rawDesc = nil
	file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_goTypes = nil
	file_waSyncdSnapshotRecovery_WAWebProtobufsSyncdSnapshotRecovery_proto_depIdxs = nil
}
