// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: waArmadilloTransportEvent/WAArmadilloTransportEvent.proto

package waArmadilloTransportEvent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransportEvent_Event_IcdcAlert_Type int32

const (
	TransportEvent_Event_IcdcAlert_NONE     TransportEvent_Event_IcdcAlert_Type = 0
	TransportEvent_Event_IcdcAlert_DETECTED TransportEvent_Event_IcdcAlert_Type = 1
	TransportEvent_Event_IcdcAlert_CLEARED  TransportEvent_Event_IcdcAlert_Type = 2
)

// Enum value maps for TransportEvent_Event_IcdcAlert_Type.
var (
	TransportEvent_Event_IcdcAlert_Type_name = map[int32]string{
		0: "NONE",
		1: "DETECTED",
		2: "CLEARED",
	}
	TransportEvent_Event_IcdcAlert_Type_value = map[string]int32{
		"NONE":     0,
		"DETECTED": 1,
		"CLEARED":  2,
	}
)

func (x TransportEvent_Event_IcdcAlert_Type) Enum() *TransportEvent_Event_IcdcAlert_Type {
	p := new(TransportEvent_Event_IcdcAlert_Type)
	*p = x
	return p
}

func (x TransportEvent_Event_IcdcAlert_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportEvent_Event_IcdcAlert_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_enumTypes[0].Descriptor()
}

func (TransportEvent_Event_IcdcAlert_Type) Type() protoreflect.EnumType {
	return &file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_enumTypes[0]
}

func (x TransportEvent_Event_IcdcAlert_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TransportEvent_Event_IcdcAlert_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TransportEvent_Event_IcdcAlert_Type(num)
	return nil
}

// Deprecated: Use TransportEvent_Event_IcdcAlert_Type.Descriptor instead.
func (TransportEvent_Event_IcdcAlert_Type) EnumDescriptor() ([]byte, []int) {
	return file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

type TransportEvent_Event_DeviceChange_Type int32

const (
	TransportEvent_Event_DeviceChange_NONE     TransportEvent_Event_DeviceChange_Type = 0
	TransportEvent_Event_DeviceChange_ADDED    TransportEvent_Event_DeviceChange_Type = 1
	TransportEvent_Event_DeviceChange_REMOVED  TransportEvent_Event_DeviceChange_Type = 2
	TransportEvent_Event_DeviceChange_REPLACED TransportEvent_Event_DeviceChange_Type = 3
)

// Enum value maps for TransportEvent_Event_DeviceChange_Type.
var (
	TransportEvent_Event_DeviceChange_Type_name = map[int32]string{
		0: "NONE",
		1: "ADDED",
		2: "REMOVED",
		3: "REPLACED",
	}
	TransportEvent_Event_DeviceChange_Type_value = map[string]int32{
		"NONE":     0,
		"ADDED":    1,
		"REMOVED":  2,
		"REPLACED": 3,
	}
)

func (x TransportEvent_Event_DeviceChange_Type) Enum() *TransportEvent_Event_DeviceChange_Type {
	p := new(TransportEvent_Event_DeviceChange_Type)
	*p = x
	return p
}

func (x TransportEvent_Event_DeviceChange_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportEvent_Event_DeviceChange_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_enumTypes[1].Descriptor()
}

func (TransportEvent_Event_DeviceChange_Type) Type() protoreflect.EnumType {
	return &file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_enumTypes[1]
}

func (x TransportEvent_Event_DeviceChange_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TransportEvent_Event_DeviceChange_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TransportEvent_Event_DeviceChange_Type(num)
	return nil
}

// Deprecated: Use TransportEvent_Event_DeviceChange_Type.Descriptor instead.
func (TransportEvent_Event_DeviceChange_Type) EnumDescriptor() ([]byte, []int) {
	return file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_rawDescGZIP(), []int{0, 0, 1, 0}
}

type TransportEvent_Placeholder_Type int32

const (
	TransportEvent_Placeholder_DECRYPTION_FAILURE  TransportEvent_Placeholder_Type = 1
	TransportEvent_Placeholder_UNAVAILABLE_MESSAGE TransportEvent_Placeholder_Type = 2
)

// Enum value maps for TransportEvent_Placeholder_Type.
var (
	TransportEvent_Placeholder_Type_name = map[int32]string{
		1: "DECRYPTION_FAILURE",
		2: "UNAVAILABLE_MESSAGE",
	}
	TransportEvent_Placeholder_Type_value = map[string]int32{
		"DECRYPTION_FAILURE":  1,
		"UNAVAILABLE_MESSAGE": 2,
	}
)

func (x TransportEvent_Placeholder_Type) Enum() *TransportEvent_Placeholder_Type {
	p := new(TransportEvent_Placeholder_Type)
	*p = x
	return p
}

func (x TransportEvent_Placeholder_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportEvent_Placeholder_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_enumTypes[2].Descriptor()
}

func (TransportEvent_Placeholder_Type) Type() protoreflect.EnumType {
	return &file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_enumTypes[2]
}

func (x TransportEvent_Placeholder_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TransportEvent_Placeholder_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TransportEvent_Placeholder_Type(num)
	return nil
}

// Deprecated: Use TransportEvent_Placeholder_Type.Descriptor instead.
func (TransportEvent_Placeholder_Type) EnumDescriptor() ([]byte, []int) {
	return file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_rawDescGZIP(), []int{0, 1, 0}
}

type TransportEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Content:
	//
	//	*TransportEvent_Placeholder_
	//	*TransportEvent_Event_
	Content isTransportEvent_Content `protobuf_oneof:"content"`
}

func (x *TransportEvent) Reset() {
	*x = TransportEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransportEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportEvent) ProtoMessage() {}

func (x *TransportEvent) ProtoReflect() protoreflect.Message {
	mi := &file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportEvent.ProtoReflect.Descriptor instead.
func (*TransportEvent) Descriptor() ([]byte, []int) {
	return file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_rawDescGZIP(), []int{0}
}

func (m *TransportEvent) GetContent() isTransportEvent_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *TransportEvent) GetPlaceholder() *TransportEvent_Placeholder {
	if x, ok := x.GetContent().(*TransportEvent_Placeholder_); ok {
		return x.Placeholder
	}
	return nil
}

func (x *TransportEvent) GetEvent() *TransportEvent_Event {
	if x, ok := x.GetContent().(*TransportEvent_Event_); ok {
		return x.Event
	}
	return nil
}

type isTransportEvent_Content interface {
	isTransportEvent_Content()
}

type TransportEvent_Placeholder_ struct {
	Placeholder *TransportEvent_Placeholder `protobuf:"bytes,1,opt,name=placeholder,oneof"`
}

type TransportEvent_Event_ struct {
	Event *TransportEvent_Event `protobuf:"bytes,2,opt,name=event,oneof"`
}

func (*TransportEvent_Placeholder_) isTransportEvent_Content() {}

func (*TransportEvent_Event_) isTransportEvent_Content() {}

type TransportEvent_Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*TransportEvent_Event_DeviceChange_
	//	*TransportEvent_Event_IcdcAlert_
	Event isTransportEvent_Event_Event `protobuf_oneof:"event"`
}

func (x *TransportEvent_Event) Reset() {
	*x = TransportEvent_Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransportEvent_Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportEvent_Event) ProtoMessage() {}

func (x *TransportEvent_Event) ProtoReflect() protoreflect.Message {
	mi := &file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportEvent_Event.ProtoReflect.Descriptor instead.
func (*TransportEvent_Event) Descriptor() ([]byte, []int) {
	return file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_rawDescGZIP(), []int{0, 0}
}

func (m *TransportEvent_Event) GetEvent() isTransportEvent_Event_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *TransportEvent_Event) GetDeviceChange() *TransportEvent_Event_DeviceChange {
	if x, ok := x.GetEvent().(*TransportEvent_Event_DeviceChange_); ok {
		return x.DeviceChange
	}
	return nil
}

func (x *TransportEvent_Event) GetIcdcAlert() *TransportEvent_Event_IcdcAlert {
	if x, ok := x.GetEvent().(*TransportEvent_Event_IcdcAlert_); ok {
		return x.IcdcAlert
	}
	return nil
}

type isTransportEvent_Event_Event interface {
	isTransportEvent_Event_Event()
}

type TransportEvent_Event_DeviceChange_ struct {
	DeviceChange *TransportEvent_Event_DeviceChange `protobuf:"bytes,1,opt,name=deviceChange,oneof"`
}

type TransportEvent_Event_IcdcAlert_ struct {
	IcdcAlert *TransportEvent_Event_IcdcAlert `protobuf:"bytes,2,opt,name=icdcAlert,oneof"`
}

func (*TransportEvent_Event_DeviceChange_) isTransportEvent_Event_Event() {}

func (*TransportEvent_Event_IcdcAlert_) isTransportEvent_Event_Event() {}

type TransportEvent_Placeholder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type *TransportEvent_Placeholder_Type `protobuf:"varint,1,opt,name=type,enum=WAArmadilloTransportEvent.TransportEvent_Placeholder_Type" json:"type,omitempty"`
}

func (x *TransportEvent_Placeholder) Reset() {
	*x = TransportEvent_Placeholder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransportEvent_Placeholder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportEvent_Placeholder) ProtoMessage() {}

func (x *TransportEvent_Placeholder) ProtoReflect() protoreflect.Message {
	mi := &file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportEvent_Placeholder.ProtoReflect.Descriptor instead.
func (*TransportEvent_Placeholder) Descriptor() ([]byte, []int) {
	return file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_rawDescGZIP(), []int{0, 1}
}

func (x *TransportEvent_Placeholder) GetType() TransportEvent_Placeholder_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return TransportEvent_Placeholder_DECRYPTION_FAILURE
}

type TransportEvent_Event_IcdcAlert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type *TransportEvent_Event_IcdcAlert_Type `protobuf:"varint,1,opt,name=type,enum=WAArmadilloTransportEvent.TransportEvent_Event_IcdcAlert_Type" json:"type,omitempty"`
}

func (x *TransportEvent_Event_IcdcAlert) Reset() {
	*x = TransportEvent_Event_IcdcAlert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransportEvent_Event_IcdcAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportEvent_Event_IcdcAlert) ProtoMessage() {}

func (x *TransportEvent_Event_IcdcAlert) ProtoReflect() protoreflect.Message {
	mi := &file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportEvent_Event_IcdcAlert.ProtoReflect.Descriptor instead.
func (*TransportEvent_Event_IcdcAlert) Descriptor() ([]byte, []int) {
	return file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *TransportEvent_Event_IcdcAlert) GetType() TransportEvent_Event_IcdcAlert_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return TransportEvent_Event_IcdcAlert_NONE
}

type TransportEvent_Event_DeviceChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type           *TransportEvent_Event_DeviceChange_Type `protobuf:"varint,1,opt,name=type,enum=WAArmadilloTransportEvent.TransportEvent_Event_DeviceChange_Type" json:"type,omitempty"`
	DeviceName     *string                                 `protobuf:"bytes,2,opt,name=deviceName" json:"deviceName,omitempty"`
	DevicePlatform *string                                 `protobuf:"bytes,3,opt,name=devicePlatform" json:"devicePlatform,omitempty"`
	DeviceModel    *string                                 `protobuf:"bytes,4,opt,name=deviceModel" json:"deviceModel,omitempty"`
}

func (x *TransportEvent_Event_DeviceChange) Reset() {
	*x = TransportEvent_Event_DeviceChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransportEvent_Event_DeviceChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportEvent_Event_DeviceChange) ProtoMessage() {}

func (x *TransportEvent_Event_DeviceChange) ProtoReflect() protoreflect.Message {
	mi := &file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportEvent_Event_DeviceChange.ProtoReflect.Descriptor instead.
func (*TransportEvent_Event_DeviceChange) Descriptor() ([]byte, []int) {
	return file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *TransportEvent_Event_DeviceChange) GetType() TransportEvent_Event_DeviceChange_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return TransportEvent_Event_DeviceChange_NONE
}

func (x *TransportEvent_Event_DeviceChange) GetDeviceName() string {
	if x != nil && x.DeviceName != nil {
		return *x.DeviceName
	}
	return ""
}

func (x *TransportEvent_Event_DeviceChange) GetDevicePlatform() string {
	if x != nil && x.DevicePlatform != nil {
		return *x.DevicePlatform
	}
	return ""
}

func (x *TransportEvent_Event_DeviceChange) GetDeviceModel() string {
	if x != nil && x.DeviceModel != nil {
		return *x.DeviceModel
	}
	return ""
}

var File_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto protoreflect.FileDescriptor

var file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_rawDesc = []byte{
	0x0a, 0x39, 0x77, 0x61, 0x41, 0x72, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x57, 0x41, 0x41, 0x72,
	0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x57, 0x41, 0x41,
	0x72, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72,
	0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0xc3, 0x07, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x59, 0x0a, 0x0b, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x35,
	0x2e, 0x57, 0x41, 0x41, 0x72, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x68,
	0x6f, 0x6c, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f,
	0x6c, 0x64, 0x65, 0x72, 0x12, 0x47, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x57, 0x41, 0x41, 0x72, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c,
	0x6f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0xe8, 0x04,
	0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x62, 0x0a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c, 0x2e,
	0x57, 0x41, 0x41, 0x72, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70,
	0x6f, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x59, 0x0a, 0x09, 0x69,
	0x63, 0x64, 0x63, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x39,
	0x2e, 0x57, 0x41, 0x41, 0x72, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x49, 0x63, 0x64, 0x63, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x48, 0x00, 0x52, 0x09, 0x69, 0x63, 0x64,
	0x63, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x1a, 0x8c, 0x01, 0x0a, 0x09, 0x49, 0x63, 0x64, 0x63, 0x41,
	0x6c, 0x65, 0x72, 0x74, 0x12, 0x52, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x3e, 0x2e, 0x57, 0x41, 0x41, 0x72, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x2e, 0x49, 0x63, 0x64, 0x63, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x2b, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x45,
	0x54, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4c, 0x45, 0x41,
	0x52, 0x45, 0x44, 0x10, 0x02, 0x1a, 0x87, 0x02, 0x0a, 0x0c, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x55, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x41, 0x2e, 0x57, 0x41, 0x41, 0x72, 0x6d, 0x61, 0x64, 0x69, 0x6c,
	0x6c, 0x6f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a,
	0x0e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x36, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x44, 0x44,
	0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x44, 0x10,
	0x02, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x44, 0x10, 0x03, 0x42,
	0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x96, 0x01, 0x0a, 0x0b, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x12, 0x4e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3a, 0x2e, 0x57, 0x41, 0x41, 0x72, 0x6d, 0x61, 0x64,
	0x69, 0x6c, 0x6c, 0x6f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x37, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x12, 0x44, 0x45, 0x43, 0x52, 0x59, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x46,
	0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x55, 0x4e, 0x41, 0x56,
	0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10,
	0x02, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x35, 0x5a, 0x33,
	0x67, 0x6f, 0x2e, 0x6d, 0x61, 0x75, 0x2e, 0x66, 0x69, 0x2f, 0x77, 0x68, 0x61, 0x74, 0x73, 0x6d,
	0x65, 0x6f, 0x77, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x41, 0x72, 0x6d, 0x61,
	0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x76,
	0x65, 0x6e, 0x74,
}

var (
	file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_rawDescOnce sync.Once
	file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_rawDescData = file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_rawDesc
)

func file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_rawDescGZIP() []byte {
	file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_rawDescOnce.Do(func() {
		file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_rawDescData = protoimpl.X.CompressGZIP(file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_rawDescData)
	})
	return file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_rawDescData
}

var file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_goTypes = []interface{}{
	(TransportEvent_Event_IcdcAlert_Type)(0),    // 0: WAArmadilloTransportEvent.TransportEvent.Event.IcdcAlert.Type
	(TransportEvent_Event_DeviceChange_Type)(0), // 1: WAArmadilloTransportEvent.TransportEvent.Event.DeviceChange.Type
	(TransportEvent_Placeholder_Type)(0),        // 2: WAArmadilloTransportEvent.TransportEvent.Placeholder.Type
	(*TransportEvent)(nil),                      // 3: WAArmadilloTransportEvent.TransportEvent
	(*TransportEvent_Event)(nil),                // 4: WAArmadilloTransportEvent.TransportEvent.Event
	(*TransportEvent_Placeholder)(nil),          // 5: WAArmadilloTransportEvent.TransportEvent.Placeholder
	(*TransportEvent_Event_IcdcAlert)(nil),      // 6: WAArmadilloTransportEvent.TransportEvent.Event.IcdcAlert
	(*TransportEvent_Event_DeviceChange)(nil),   // 7: WAArmadilloTransportEvent.TransportEvent.Event.DeviceChange
}
var file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_depIdxs = []int32{
	5, // 0: WAArmadilloTransportEvent.TransportEvent.placeholder:type_name -> WAArmadilloTransportEvent.TransportEvent.Placeholder
	4, // 1: WAArmadilloTransportEvent.TransportEvent.event:type_name -> WAArmadilloTransportEvent.TransportEvent.Event
	7, // 2: WAArmadilloTransportEvent.TransportEvent.Event.deviceChange:type_name -> WAArmadilloTransportEvent.TransportEvent.Event.DeviceChange
	6, // 3: WAArmadilloTransportEvent.TransportEvent.Event.icdcAlert:type_name -> WAArmadilloTransportEvent.TransportEvent.Event.IcdcAlert
	2, // 4: WAArmadilloTransportEvent.TransportEvent.Placeholder.type:type_name -> WAArmadilloTransportEvent.TransportEvent.Placeholder.Type
	0, // 5: WAArmadilloTransportEvent.TransportEvent.Event.IcdcAlert.type:type_name -> WAArmadilloTransportEvent.TransportEvent.Event.IcdcAlert.Type
	1, // 6: WAArmadilloTransportEvent.TransportEvent.Event.DeviceChange.type:type_name -> WAArmadilloTransportEvent.TransportEvent.Event.DeviceChange.Type
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_init() }
func file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_init() {
	if File_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransportEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransportEvent_Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransportEvent_Placeholder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransportEvent_Event_IcdcAlert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransportEvent_Event_DeviceChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*TransportEvent_Placeholder_)(nil),
		(*TransportEvent_Event_)(nil),
	}
	file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*TransportEvent_Event_DeviceChange_)(nil),
		(*TransportEvent_Event_IcdcAlert_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_goTypes,
		DependencyIndexes: file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_depIdxs,
		EnumInfos:         file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_enumTypes,
		MessageInfos:      file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_msgTypes,
	}.Build()
	File_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto = out.File
	file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_rawDesc = nil
	file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_goTypes = nil
	file_waArmadilloTransportEvent_WAArmadilloTransportEvent_proto_depIdxs = nil
}
