// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: waArmadilloBackupCommon/WAArmadilloBackupCommon.proto

package waArmadilloBackupCommon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subprotocol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	Version *int32 `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
}

func (x *Subprotocol) Reset() {
	*x = Subprotocol{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Subprotocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subprotocol) ProtoMessage() {}

func (x *Subprotocol) ProtoReflect() protoreflect.Message {
	mi := &file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subprotocol.ProtoReflect.Descriptor instead.
func (*Subprotocol) Descriptor() ([]byte, []int) {
	return file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDescGZIP(), []int{0}
}

func (x *Subprotocol) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Subprotocol) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

type FrankingMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FrankingTag  []byte `protobuf:"bytes,3,opt,name=frankingTag" json:"frankingTag,omitempty"`
	ReportingTag []byte `protobuf:"bytes,4,opt,name=reportingTag" json:"reportingTag,omitempty"`
}

func (x *FrankingMetadata) Reset() {
	*x = FrankingMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FrankingMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrankingMetadata) ProtoMessage() {}

func (x *FrankingMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrankingMetadata.ProtoReflect.Descriptor instead.
func (*FrankingMetadata) Descriptor() ([]byte, []int) {
	return file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDescGZIP(), []int{1}
}

func (x *FrankingMetadata) GetFrankingTag() []byte {
	if x != nil {
		return x.FrankingTag
	}
	return nil
}

func (x *FrankingMetadata) GetReportingTag() []byte {
	if x != nil {
		return x.ReportingTag
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderID            *string           `protobuf:"bytes,1,opt,name=senderID" json:"senderID,omitempty"`
	MessageID           *string           `protobuf:"bytes,2,opt,name=messageID" json:"messageID,omitempty"`
	TimestampMS         *int64            `protobuf:"varint,3,opt,name=timestampMS" json:"timestampMS,omitempty"`
	FrankingMetadata    *FrankingMetadata `protobuf:"bytes,4,opt,name=frankingMetadata" json:"frankingMetadata,omitempty"`
	PayloadVersion      *int32            `protobuf:"varint,5,opt,name=payloadVersion" json:"payloadVersion,omitempty"`
	FutureProofBehavior *int32            `protobuf:"varint,6,opt,name=futureProofBehavior" json:"futureProofBehavior,omitempty"`
	ThreadTypeTag       *int32            `protobuf:"varint,7,opt,name=threadTypeTag" json:"threadTypeTag,omitempty"`
	ClientTimestampMS   *int64            `protobuf:"varint,8,opt,name=clientTimestampMS" json:"clientTimestampMS,omitempty"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDescGZIP(), []int{2}
}

func (x *Metadata) GetSenderID() string {
	if x != nil && x.SenderID != nil {
		return *x.SenderID
	}
	return ""
}

func (x *Metadata) GetMessageID() string {
	if x != nil && x.MessageID != nil {
		return *x.MessageID
	}
	return ""
}

func (x *Metadata) GetTimestampMS() int64 {
	if x != nil && x.TimestampMS != nil {
		return *x.TimestampMS
	}
	return 0
}

func (x *Metadata) GetFrankingMetadata() *FrankingMetadata {
	if x != nil {
		return x.FrankingMetadata
	}
	return nil
}

func (x *Metadata) GetPayloadVersion() int32 {
	if x != nil && x.PayloadVersion != nil {
		return *x.PayloadVersion
	}
	return 0
}

func (x *Metadata) GetFutureProofBehavior() int32 {
	if x != nil && x.FutureProofBehavior != nil {
		return *x.FutureProofBehavior
	}
	return 0
}

func (x *Metadata) GetThreadTypeTag() int32 {
	if x != nil && x.ThreadTypeTag != nil {
		return *x.ThreadTypeTag
	}
	return 0
}

func (x *Metadata) GetClientTimestampMS() int64 {
	if x != nil && x.ClientTimestampMS != nil {
		return *x.ClientTimestampMS
	}
	return 0
}

var File_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto protoreflect.FileDescriptor

var file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDesc = []byte{
	0x0a, 0x35, 0x77, 0x61, 0x41, 0x72, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x42, 0x61, 0x63,
	0x6b, 0x75, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x57, 0x41, 0x41, 0x72, 0x6d, 0x61,
	0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x57, 0x41, 0x41, 0x72, 0x6d, 0x61, 0x64,
	0x69, 0x6c, 0x6c, 0x6f, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x22, 0x41, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0x58, 0x0a, 0x10, 0x46, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x72, 0x61, 0x6e, 0x6b,
	0x69, 0x6e, 0x67, 0x54, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x66, 0x72,
	0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0c, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x67, 0x22, 0xeb, 0x02,
	0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x4d, 0x53, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x4d, 0x53, 0x12, 0x55, 0x0a, 0x10, 0x66, 0x72, 0x61, 0x6e, 0x6b, 0x69,
	0x6e, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x29, 0x2e, 0x57, 0x41, 0x41, 0x72, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x42, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x46, 0x72, 0x61, 0x6e, 0x6b,
	0x69, 0x6e, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x10, 0x66, 0x72, 0x61,
	0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x26, 0x0a,
	0x0e, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x13, 0x66, 0x75, 0x74, 0x75, 0x72, 0x65, 0x50,
	0x72, 0x6f, 0x6f, 0x66, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x13, 0x66, 0x75, 0x74, 0x75, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x42,
	0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x68, 0x72, 0x65, 0x61,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x54, 0x61, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d,
	0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x54, 0x61, 0x67, 0x12, 0x2c, 0x0a,
	0x11, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x4d, 0x53, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x53, 0x42, 0x41, 0x5a, 0x3f, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x6e, 0x67, 0x2d, 0x78,
	0x69, 0x61, 0x6e, 0x67, 0x31, 0x33, 0x2f, 0x77, 0x68, 0x61, 0x74, 0x73, 0x6d, 0x65, 0x6f, 0x77,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x41, 0x72, 0x6d, 0x61, 0x64, 0x69, 0x6c,
	0x6c, 0x6f, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
}

var (
	file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDescOnce sync.Once
	file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDescData = file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDesc
)

func file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDescGZIP() []byte {
	file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDescOnce.Do(func() {
		file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDescData = protoimpl.X.CompressGZIP(file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDescData)
	})
	return file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDescData
}

var file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_goTypes = []interface{}{
	(*Subprotocol)(nil),      // 0: WAArmadilloBackupCommon.Subprotocol
	(*FrankingMetadata)(nil), // 1: WAArmadilloBackupCommon.FrankingMetadata
	(*Metadata)(nil),         // 2: WAArmadilloBackupCommon.Metadata
}
var file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_depIdxs = []int32{
	1, // 0: WAArmadilloBackupCommon.Metadata.frankingMetadata:type_name -> WAArmadilloBackupCommon.FrankingMetadata
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_init() }
func file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_init() {
	if File_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Subprotocol); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FrankingMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_goTypes,
		DependencyIndexes: file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_depIdxs,
		MessageInfos:      file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_msgTypes,
	}.Build()
	File_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto = out.File
	file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDesc = nil
	file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_goTypes = nil
	file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_depIdxs = nil
}
