// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: waStatusAttributions/WAStatusAttributions.proto

package waStatusAttributions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusAttribution_Type int32

const (
	StatusAttribution_UNKNOWN        StatusAttribution_Type = 0
	StatusAttribution_RESHARE        StatusAttribution_Type = 1
	StatusAttribution_EXTERNAL_SHARE StatusAttribution_Type = 2
	StatusAttribution_MUSIC          StatusAttribution_Type = 3
	StatusAttribution_STATUS_MENTION StatusAttribution_Type = 4
	StatusAttribution_GROUP_STATUS   StatusAttribution_Type = 5
	StatusAttribution_RL_ATTRIBUTION StatusAttribution_Type = 6
	StatusAttribution_AI_CREATED     StatusAttribution_Type = 7
	StatusAttribution_LAYOUTS        StatusAttribution_Type = 8
)

// Enum value maps for StatusAttribution_Type.
var (
	StatusAttribution_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "RESHARE",
		2: "EXTERNAL_SHARE",
		3: "MUSIC",
		4: "STATUS_MENTION",
		5: "GROUP_STATUS",
		6: "RL_ATTRIBUTION",
		7: "AI_CREATED",
		8: "LAYOUTS",
	}
	StatusAttribution_Type_value = map[string]int32{
		"UNKNOWN":        0,
		"RESHARE":        1,
		"EXTERNAL_SHARE": 2,
		"MUSIC":          3,
		"STATUS_MENTION": 4,
		"GROUP_STATUS":   5,
		"RL_ATTRIBUTION": 6,
		"AI_CREATED":     7,
		"LAYOUTS":        8,
	}
)

func (x StatusAttribution_Type) Enum() *StatusAttribution_Type {
	p := new(StatusAttribution_Type)
	*p = x
	return p
}

func (x StatusAttribution_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusAttribution_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_waStatusAttributions_WAStatusAttributions_proto_enumTypes[0].Descriptor()
}

func (StatusAttribution_Type) Type() protoreflect.EnumType {
	return &file_waStatusAttributions_WAStatusAttributions_proto_enumTypes[0]
}

func (x StatusAttribution_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *StatusAttribution_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = StatusAttribution_Type(num)
	return nil
}

// Deprecated: Use StatusAttribution_Type.Descriptor instead.
func (StatusAttribution_Type) EnumDescriptor() ([]byte, []int) {
	return file_waStatusAttributions_WAStatusAttributions_proto_rawDescGZIP(), []int{0, 0}
}

type StatusAttribution_AiCreatedAttribution_Source int32

const (
	StatusAttribution_AiCreatedAttribution_UNKNOWN        StatusAttribution_AiCreatedAttribution_Source = 0
	StatusAttribution_AiCreatedAttribution_STATUS_MIMICRY StatusAttribution_AiCreatedAttribution_Source = 1
)

// Enum value maps for StatusAttribution_AiCreatedAttribution_Source.
var (
	StatusAttribution_AiCreatedAttribution_Source_name = map[int32]string{
		0: "UNKNOWN",
		1: "STATUS_MIMICRY",
	}
	StatusAttribution_AiCreatedAttribution_Source_value = map[string]int32{
		"UNKNOWN":        0,
		"STATUS_MIMICRY": 1,
	}
)

func (x StatusAttribution_AiCreatedAttribution_Source) Enum() *StatusAttribution_AiCreatedAttribution_Source {
	p := new(StatusAttribution_AiCreatedAttribution_Source)
	*p = x
	return p
}

func (x StatusAttribution_AiCreatedAttribution_Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusAttribution_AiCreatedAttribution_Source) Descriptor() protoreflect.EnumDescriptor {
	return file_waStatusAttributions_WAStatusAttributions_proto_enumTypes[1].Descriptor()
}

func (StatusAttribution_AiCreatedAttribution_Source) Type() protoreflect.EnumType {
	return &file_waStatusAttributions_WAStatusAttributions_proto_enumTypes[1]
}

func (x StatusAttribution_AiCreatedAttribution_Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *StatusAttribution_AiCreatedAttribution_Source) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = StatusAttribution_AiCreatedAttribution_Source(num)
	return nil
}

// Deprecated: Use StatusAttribution_AiCreatedAttribution_Source.Descriptor instead.
func (StatusAttribution_AiCreatedAttribution_Source) EnumDescriptor() ([]byte, []int) {
	return file_waStatusAttributions_WAStatusAttributions_proto_rawDescGZIP(), []int{0, 0, 0}
}

type StatusAttribution_RLAttribution_Source int32

const (
	StatusAttribution_RLAttribution_UNKNOWN              StatusAttribution_RLAttribution_Source = 0
	StatusAttribution_RLAttribution_RAY_BAN_META_GLASSES StatusAttribution_RLAttribution_Source = 1
	StatusAttribution_RLAttribution_OAKLEY_META_GLASSES  StatusAttribution_RLAttribution_Source = 2
	StatusAttribution_RLAttribution_HYPERNOVA_GLASSES    StatusAttribution_RLAttribution_Source = 3
)

// Enum value maps for StatusAttribution_RLAttribution_Source.
var (
	StatusAttribution_RLAttribution_Source_name = map[int32]string{
		0: "UNKNOWN",
		1: "RAY_BAN_META_GLASSES",
		2: "OAKLEY_META_GLASSES",
		3: "HYPERNOVA_GLASSES",
	}
	StatusAttribution_RLAttribution_Source_value = map[string]int32{
		"UNKNOWN":              0,
		"RAY_BAN_META_GLASSES": 1,
		"OAKLEY_META_GLASSES":  2,
		"HYPERNOVA_GLASSES":    3,
	}
)

func (x StatusAttribution_RLAttribution_Source) Enum() *StatusAttribution_RLAttribution_Source {
	p := new(StatusAttribution_RLAttribution_Source)
	*p = x
	return p
}

func (x StatusAttribution_RLAttribution_Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusAttribution_RLAttribution_Source) Descriptor() protoreflect.EnumDescriptor {
	return file_waStatusAttributions_WAStatusAttributions_proto_enumTypes[2].Descriptor()
}

func (StatusAttribution_RLAttribution_Source) Type() protoreflect.EnumType {
	return &file_waStatusAttributions_WAStatusAttributions_proto_enumTypes[2]
}

func (x StatusAttribution_RLAttribution_Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *StatusAttribution_RLAttribution_Source) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = StatusAttribution_RLAttribution_Source(num)
	return nil
}

// Deprecated: Use StatusAttribution_RLAttribution_Source.Descriptor instead.
func (StatusAttribution_RLAttribution_Source) EnumDescriptor() ([]byte, []int) {
	return file_waStatusAttributions_WAStatusAttributions_proto_rawDescGZIP(), []int{0, 1, 0}
}

type StatusAttribution_ExternalShare_Source int32

const (
	StatusAttribution_ExternalShare_UNKNOWN       StatusAttribution_ExternalShare_Source = 0
	StatusAttribution_ExternalShare_INSTAGRAM     StatusAttribution_ExternalShare_Source = 1
	StatusAttribution_ExternalShare_FACEBOOK      StatusAttribution_ExternalShare_Source = 2
	StatusAttribution_ExternalShare_MESSENGER     StatusAttribution_ExternalShare_Source = 3
	StatusAttribution_ExternalShare_SPOTIFY       StatusAttribution_ExternalShare_Source = 4
	StatusAttribution_ExternalShare_YOUTUBE       StatusAttribution_ExternalShare_Source = 5
	StatusAttribution_ExternalShare_PINTEREST     StatusAttribution_ExternalShare_Source = 6
	StatusAttribution_ExternalShare_THREADS       StatusAttribution_ExternalShare_Source = 7
	StatusAttribution_ExternalShare_APPLE_MUSIC   StatusAttribution_ExternalShare_Source = 8
	StatusAttribution_ExternalShare_SHARECHAT     StatusAttribution_ExternalShare_Source = 9
	StatusAttribution_ExternalShare_GOOGLE_PHOTOS StatusAttribution_ExternalShare_Source = 10
)

// Enum value maps for StatusAttribution_ExternalShare_Source.
var (
	StatusAttribution_ExternalShare_Source_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "INSTAGRAM",
		2:  "FACEBOOK",
		3:  "MESSENGER",
		4:  "SPOTIFY",
		5:  "YOUTUBE",
		6:  "PINTEREST",
		7:  "THREADS",
		8:  "APPLE_MUSIC",
		9:  "SHARECHAT",
		10: "GOOGLE_PHOTOS",
	}
	StatusAttribution_ExternalShare_Source_value = map[string]int32{
		"UNKNOWN":       0,
		"INSTAGRAM":     1,
		"FACEBOOK":      2,
		"MESSENGER":     3,
		"SPOTIFY":       4,
		"YOUTUBE":       5,
		"PINTEREST":     6,
		"THREADS":       7,
		"APPLE_MUSIC":   8,
		"SHARECHAT":     9,
		"GOOGLE_PHOTOS": 10,
	}
)

func (x StatusAttribution_ExternalShare_Source) Enum() *StatusAttribution_ExternalShare_Source {
	p := new(StatusAttribution_ExternalShare_Source)
	*p = x
	return p
}

func (x StatusAttribution_ExternalShare_Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusAttribution_ExternalShare_Source) Descriptor() protoreflect.EnumDescriptor {
	return file_waStatusAttributions_WAStatusAttributions_proto_enumTypes[3].Descriptor()
}

func (StatusAttribution_ExternalShare_Source) Type() protoreflect.EnumType {
	return &file_waStatusAttributions_WAStatusAttributions_proto_enumTypes[3]
}

func (x StatusAttribution_ExternalShare_Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *StatusAttribution_ExternalShare_Source) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = StatusAttribution_ExternalShare_Source(num)
	return nil
}

// Deprecated: Use StatusAttribution_ExternalShare_Source.Descriptor instead.
func (StatusAttribution_ExternalShare_Source) EnumDescriptor() ([]byte, []int) {
	return file_waStatusAttributions_WAStatusAttributions_proto_rawDescGZIP(), []int{0, 2, 0}
}

type StatusAttribution_StatusReshare_Source int32

const (
	StatusAttribution_StatusReshare_UNKNOWN          StatusAttribution_StatusReshare_Source = 0
	StatusAttribution_StatusReshare_INTERNAL_RESHARE StatusAttribution_StatusReshare_Source = 1
	StatusAttribution_StatusReshare_MENTION_RESHARE  StatusAttribution_StatusReshare_Source = 2
	StatusAttribution_StatusReshare_CHANNEL_RESHARE  StatusAttribution_StatusReshare_Source = 3
	StatusAttribution_StatusReshare_FORWARD          StatusAttribution_StatusReshare_Source = 4
)

// Enum value maps for StatusAttribution_StatusReshare_Source.
var (
	StatusAttribution_StatusReshare_Source_name = map[int32]string{
		0: "UNKNOWN",
		1: "INTERNAL_RESHARE",
		2: "MENTION_RESHARE",
		3: "CHANNEL_RESHARE",
		4: "FORWARD",
	}
	StatusAttribution_StatusReshare_Source_value = map[string]int32{
		"UNKNOWN":          0,
		"INTERNAL_RESHARE": 1,
		"MENTION_RESHARE":  2,
		"CHANNEL_RESHARE":  3,
		"FORWARD":          4,
	}
)

func (x StatusAttribution_StatusReshare_Source) Enum() *StatusAttribution_StatusReshare_Source {
	p := new(StatusAttribution_StatusReshare_Source)
	*p = x
	return p
}

func (x StatusAttribution_StatusReshare_Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusAttribution_StatusReshare_Source) Descriptor() protoreflect.EnumDescriptor {
	return file_waStatusAttributions_WAStatusAttributions_proto_enumTypes[4].Descriptor()
}

func (StatusAttribution_StatusReshare_Source) Type() protoreflect.EnumType {
	return &file_waStatusAttributions_WAStatusAttributions_proto_enumTypes[4]
}

func (x StatusAttribution_StatusReshare_Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *StatusAttribution_StatusReshare_Source) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = StatusAttribution_StatusReshare_Source(num)
	return nil
}

// Deprecated: Use StatusAttribution_StatusReshare_Source.Descriptor instead.
func (StatusAttribution_StatusReshare_Source) EnumDescriptor() ([]byte, []int) {
	return file_waStatusAttributions_WAStatusAttributions_proto_rawDescGZIP(), []int{0, 3, 0}
}

type StatusAttribution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to AttributionData:
	//
	//	*StatusAttribution_StatusReshare_
	//	*StatusAttribution_ExternalShare_
	//	*StatusAttribution_Music_
	//	*StatusAttribution_GroupStatus_
	//	*StatusAttribution_RlAttribution
	//	*StatusAttribution_AiCreatedAttribution_
	AttributionData isStatusAttribution_AttributionData `protobuf_oneof:"attributionData"`
	Type            *StatusAttribution_Type             `protobuf:"varint,1,opt,name=type,enum=WAStatusAttributions.StatusAttribution_Type" json:"type,omitempty"`
	ActionURL       *string                             `protobuf:"bytes,2,opt,name=actionURL" json:"actionURL,omitempty"`
}

func (x *StatusAttribution) Reset() {
	*x = StatusAttribution{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusAttribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusAttribution) ProtoMessage() {}

func (x *StatusAttribution) ProtoReflect() protoreflect.Message {
	mi := &file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusAttribution.ProtoReflect.Descriptor instead.
func (*StatusAttribution) Descriptor() ([]byte, []int) {
	return file_waStatusAttributions_WAStatusAttributions_proto_rawDescGZIP(), []int{0}
}

func (m *StatusAttribution) GetAttributionData() isStatusAttribution_AttributionData {
	if m != nil {
		return m.AttributionData
	}
	return nil
}

func (x *StatusAttribution) GetStatusReshare() *StatusAttribution_StatusReshare {
	if x, ok := x.GetAttributionData().(*StatusAttribution_StatusReshare_); ok {
		return x.StatusReshare
	}
	return nil
}

func (x *StatusAttribution) GetExternalShare() *StatusAttribution_ExternalShare {
	if x, ok := x.GetAttributionData().(*StatusAttribution_ExternalShare_); ok {
		return x.ExternalShare
	}
	return nil
}

func (x *StatusAttribution) GetMusic() *StatusAttribution_Music {
	if x, ok := x.GetAttributionData().(*StatusAttribution_Music_); ok {
		return x.Music
	}
	return nil
}

func (x *StatusAttribution) GetGroupStatus() *StatusAttribution_GroupStatus {
	if x, ok := x.GetAttributionData().(*StatusAttribution_GroupStatus_); ok {
		return x.GroupStatus
	}
	return nil
}

func (x *StatusAttribution) GetRlAttribution() *StatusAttribution_RLAttribution {
	if x, ok := x.GetAttributionData().(*StatusAttribution_RlAttribution); ok {
		return x.RlAttribution
	}
	return nil
}

func (x *StatusAttribution) GetAiCreatedAttribution() *StatusAttribution_AiCreatedAttribution {
	if x, ok := x.GetAttributionData().(*StatusAttribution_AiCreatedAttribution_); ok {
		return x.AiCreatedAttribution
	}
	return nil
}

func (x *StatusAttribution) GetType() StatusAttribution_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return StatusAttribution_UNKNOWN
}

func (x *StatusAttribution) GetActionURL() string {
	if x != nil && x.ActionURL != nil {
		return *x.ActionURL
	}
	return ""
}

type isStatusAttribution_AttributionData interface {
	isStatusAttribution_AttributionData()
}

type StatusAttribution_StatusReshare_ struct {
	StatusReshare *StatusAttribution_StatusReshare `protobuf:"bytes,3,opt,name=statusReshare,oneof"`
}

type StatusAttribution_ExternalShare_ struct {
	ExternalShare *StatusAttribution_ExternalShare `protobuf:"bytes,4,opt,name=externalShare,oneof"`
}

type StatusAttribution_Music_ struct {
	Music *StatusAttribution_Music `protobuf:"bytes,5,opt,name=music,oneof"`
}

type StatusAttribution_GroupStatus_ struct {
	GroupStatus *StatusAttribution_GroupStatus `protobuf:"bytes,6,opt,name=groupStatus,oneof"`
}

type StatusAttribution_RlAttribution struct {
	RlAttribution *StatusAttribution_RLAttribution `protobuf:"bytes,7,opt,name=rlAttribution,oneof"`
}

type StatusAttribution_AiCreatedAttribution_ struct {
	AiCreatedAttribution *StatusAttribution_AiCreatedAttribution `protobuf:"bytes,8,opt,name=aiCreatedAttribution,oneof"`
}

func (*StatusAttribution_StatusReshare_) isStatusAttribution_AttributionData() {}

func (*StatusAttribution_ExternalShare_) isStatusAttribution_AttributionData() {}

func (*StatusAttribution_Music_) isStatusAttribution_AttributionData() {}

func (*StatusAttribution_GroupStatus_) isStatusAttribution_AttributionData() {}

func (*StatusAttribution_RlAttribution) isStatusAttribution_AttributionData() {}

func (*StatusAttribution_AiCreatedAttribution_) isStatusAttribution_AttributionData() {}

type StatusAttribution_AiCreatedAttribution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source *StatusAttribution_AiCreatedAttribution_Source `protobuf:"varint,1,opt,name=source,enum=WAStatusAttributions.StatusAttribution_AiCreatedAttribution_Source" json:"source,omitempty"`
}

func (x *StatusAttribution_AiCreatedAttribution) Reset() {
	*x = StatusAttribution_AiCreatedAttribution{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusAttribution_AiCreatedAttribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusAttribution_AiCreatedAttribution) ProtoMessage() {}

func (x *StatusAttribution_AiCreatedAttribution) ProtoReflect() protoreflect.Message {
	mi := &file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusAttribution_AiCreatedAttribution.ProtoReflect.Descriptor instead.
func (*StatusAttribution_AiCreatedAttribution) Descriptor() ([]byte, []int) {
	return file_waStatusAttributions_WAStatusAttributions_proto_rawDescGZIP(), []int{0, 0}
}

func (x *StatusAttribution_AiCreatedAttribution) GetSource() StatusAttribution_AiCreatedAttribution_Source {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return StatusAttribution_AiCreatedAttribution_UNKNOWN
}

type StatusAttribution_RLAttribution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source *StatusAttribution_RLAttribution_Source `protobuf:"varint,1,opt,name=source,enum=WAStatusAttributions.StatusAttribution_RLAttribution_Source" json:"source,omitempty"`
}

func (x *StatusAttribution_RLAttribution) Reset() {
	*x = StatusAttribution_RLAttribution{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusAttribution_RLAttribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusAttribution_RLAttribution) ProtoMessage() {}

func (x *StatusAttribution_RLAttribution) ProtoReflect() protoreflect.Message {
	mi := &file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusAttribution_RLAttribution.ProtoReflect.Descriptor instead.
func (*StatusAttribution_RLAttribution) Descriptor() ([]byte, []int) {
	return file_waStatusAttributions_WAStatusAttributions_proto_rawDescGZIP(), []int{0, 1}
}

func (x *StatusAttribution_RLAttribution) GetSource() StatusAttribution_RLAttribution_Source {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return StatusAttribution_RLAttribution_UNKNOWN
}

type StatusAttribution_ExternalShare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionURL         *string                                 `protobuf:"bytes,1,opt,name=actionURL" json:"actionURL,omitempty"`
	Source            *StatusAttribution_ExternalShare_Source `protobuf:"varint,2,opt,name=source,enum=WAStatusAttributions.StatusAttribution_ExternalShare_Source" json:"source,omitempty"`
	Duration          *int32                                  `protobuf:"varint,3,opt,name=duration" json:"duration,omitempty"`
	ActionFallbackURL *string                                 `protobuf:"bytes,4,opt,name=actionFallbackURL" json:"actionFallbackURL,omitempty"`
}

func (x *StatusAttribution_ExternalShare) Reset() {
	*x = StatusAttribution_ExternalShare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusAttribution_ExternalShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusAttribution_ExternalShare) ProtoMessage() {}

func (x *StatusAttribution_ExternalShare) ProtoReflect() protoreflect.Message {
	mi := &file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusAttribution_ExternalShare.ProtoReflect.Descriptor instead.
func (*StatusAttribution_ExternalShare) Descriptor() ([]byte, []int) {
	return file_waStatusAttributions_WAStatusAttributions_proto_rawDescGZIP(), []int{0, 2}
}

func (x *StatusAttribution_ExternalShare) GetActionURL() string {
	if x != nil && x.ActionURL != nil {
		return *x.ActionURL
	}
	return ""
}

func (x *StatusAttribution_ExternalShare) GetSource() StatusAttribution_ExternalShare_Source {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return StatusAttribution_ExternalShare_UNKNOWN
}

func (x *StatusAttribution_ExternalShare) GetDuration() int32 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

func (x *StatusAttribution_ExternalShare) GetActionFallbackURL() string {
	if x != nil && x.ActionFallbackURL != nil {
		return *x.ActionFallbackURL
	}
	return ""
}

type StatusAttribution_StatusReshare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source   *StatusAttribution_StatusReshare_Source   `protobuf:"varint,1,opt,name=source,enum=WAStatusAttributions.StatusAttribution_StatusReshare_Source" json:"source,omitempty"`
	Metadata *StatusAttribution_StatusReshare_Metadata `protobuf:"bytes,2,opt,name=metadata" json:"metadata,omitempty"`
}

func (x *StatusAttribution_StatusReshare) Reset() {
	*x = StatusAttribution_StatusReshare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusAttribution_StatusReshare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusAttribution_StatusReshare) ProtoMessage() {}

func (x *StatusAttribution_StatusReshare) ProtoReflect() protoreflect.Message {
	mi := &file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusAttribution_StatusReshare.ProtoReflect.Descriptor instead.
func (*StatusAttribution_StatusReshare) Descriptor() ([]byte, []int) {
	return file_waStatusAttributions_WAStatusAttributions_proto_rawDescGZIP(), []int{0, 3}
}

func (x *StatusAttribution_StatusReshare) GetSource() StatusAttribution_StatusReshare_Source {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return StatusAttribution_StatusReshare_UNKNOWN
}

func (x *StatusAttribution_StatusReshare) GetMetadata() *StatusAttribution_StatusReshare_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StatusAttribution_GroupStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorJID *string `protobuf:"bytes,1,opt,name=authorJID" json:"authorJID,omitempty"`
}

func (x *StatusAttribution_GroupStatus) Reset() {
	*x = StatusAttribution_GroupStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusAttribution_GroupStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusAttribution_GroupStatus) ProtoMessage() {}

func (x *StatusAttribution_GroupStatus) ProtoReflect() protoreflect.Message {
	mi := &file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusAttribution_GroupStatus.ProtoReflect.Descriptor instead.
func (*StatusAttribution_GroupStatus) Descriptor() ([]byte, []int) {
	return file_waStatusAttributions_WAStatusAttributions_proto_rawDescGZIP(), []int{0, 4}
}

func (x *StatusAttribution_GroupStatus) GetAuthorJID() string {
	if x != nil && x.AuthorJID != nil {
		return *x.AuthorJID
	}
	return ""
}

type StatusAttribution_Music struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorName        *string `protobuf:"bytes,1,opt,name=authorName" json:"authorName,omitempty"`
	SongID            *string `protobuf:"bytes,2,opt,name=songID" json:"songID,omitempty"`
	Title             *string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Author            *string `protobuf:"bytes,4,opt,name=author" json:"author,omitempty"`
	ArtistAttribution *string `protobuf:"bytes,5,opt,name=artistAttribution" json:"artistAttribution,omitempty"`
	IsExplicit        *bool   `protobuf:"varint,6,opt,name=isExplicit" json:"isExplicit,omitempty"`
}

func (x *StatusAttribution_Music) Reset() {
	*x = StatusAttribution_Music{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusAttribution_Music) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusAttribution_Music) ProtoMessage() {}

func (x *StatusAttribution_Music) ProtoReflect() protoreflect.Message {
	mi := &file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusAttribution_Music.ProtoReflect.Descriptor instead.
func (*StatusAttribution_Music) Descriptor() ([]byte, []int) {
	return file_waStatusAttributions_WAStatusAttributions_proto_rawDescGZIP(), []int{0, 5}
}

func (x *StatusAttribution_Music) GetAuthorName() string {
	if x != nil && x.AuthorName != nil {
		return *x.AuthorName
	}
	return ""
}

func (x *StatusAttribution_Music) GetSongID() string {
	if x != nil && x.SongID != nil {
		return *x.SongID
	}
	return ""
}

func (x *StatusAttribution_Music) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *StatusAttribution_Music) GetAuthor() string {
	if x != nil && x.Author != nil {
		return *x.Author
	}
	return ""
}

func (x *StatusAttribution_Music) GetArtistAttribution() string {
	if x != nil && x.ArtistAttribution != nil {
		return *x.ArtistAttribution
	}
	return ""
}

func (x *StatusAttribution_Music) GetIsExplicit() bool {
	if x != nil && x.IsExplicit != nil {
		return *x.IsExplicit
	}
	return false
}

type StatusAttribution_StatusReshare_Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Duration            *int32  `protobuf:"varint,1,opt,name=duration" json:"duration,omitempty"`
	ChannelJID          *string `protobuf:"bytes,2,opt,name=channelJID" json:"channelJID,omitempty"`
	ChannelMessageID    *int32  `protobuf:"varint,3,opt,name=channelMessageID" json:"channelMessageID,omitempty"`
	HasMultipleReshares *bool   `protobuf:"varint,4,opt,name=hasMultipleReshares" json:"hasMultipleReshares,omitempty"`
}

func (x *StatusAttribution_StatusReshare_Metadata) Reset() {
	*x = StatusAttribution_StatusReshare_Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusAttribution_StatusReshare_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusAttribution_StatusReshare_Metadata) ProtoMessage() {}

func (x *StatusAttribution_StatusReshare_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusAttribution_StatusReshare_Metadata.ProtoReflect.Descriptor instead.
func (*StatusAttribution_StatusReshare_Metadata) Descriptor() ([]byte, []int) {
	return file_waStatusAttributions_WAStatusAttributions_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *StatusAttribution_StatusReshare_Metadata) GetDuration() int32 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

func (x *StatusAttribution_StatusReshare_Metadata) GetChannelJID() string {
	if x != nil && x.ChannelJID != nil {
		return *x.ChannelJID
	}
	return ""
}

func (x *StatusAttribution_StatusReshare_Metadata) GetChannelMessageID() int32 {
	if x != nil && x.ChannelMessageID != nil {
		return *x.ChannelMessageID
	}
	return 0
}

func (x *StatusAttribution_StatusReshare_Metadata) GetHasMultipleReshares() bool {
	if x != nil && x.HasMultipleReshares != nil {
		return *x.HasMultipleReshares
	}
	return false
}

var File_waStatusAttributions_WAStatusAttributions_proto protoreflect.FileDescriptor

var file_waStatusAttributions_WAStatusAttributions_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x77, 0x61, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x57, 0x41, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x14, 0x57, 0x41, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xf1, 0x11, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x5d, 0x0a,
	0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x57, 0x41, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65, 0x12, 0x5d, 0x0a, 0x0d,
	0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x57, 0x41, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x78, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x65, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x65, 0x12, 0x45, 0x0a, 0x05, 0x6d,
	0x75, 0x73, 0x69, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x57, 0x41, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x48, 0x00, 0x52, 0x05, 0x6d, 0x75, 0x73,
	0x69, 0x63, 0x12, 0x57, 0x0a, 0x0b, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x57, 0x41, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x0b,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x5d, 0x0a, 0x0d, 0x72,
	0x6c, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x35, 0x2e, 0x57, 0x41, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x4c, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x6c, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x72, 0x0a, 0x14, 0x61, 0x69,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x57, 0x41, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x41, 0x69, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x14, 0x61, 0x69, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x40,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x57,
	0x41, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x52, 0x4c, 0x1a, 0x9e,
	0x01, 0x0a, 0x14, 0x41, 0x69, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x5b, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x43, 0x2e, 0x57, 0x41, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x41, 0x69, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x22, 0x29, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4d, 0x49, 0x4d, 0x49, 0x43, 0x52, 0x59, 0x10, 0x01, 0x1a,
	0xc6, 0x01, 0x0a, 0x0d, 0x52, 0x4c, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x54, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x3c, 0x2e, 0x57, 0x41, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x4c, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52,
	0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x5f, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x18,
	0x0a, 0x14, 0x52, 0x41, 0x59, 0x5f, 0x42, 0x41, 0x4e, 0x5f, 0x4d, 0x45, 0x54, 0x41, 0x5f, 0x47,
	0x4c, 0x41, 0x53, 0x53, 0x45, 0x53, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x4f, 0x41, 0x4b, 0x4c,
	0x45, 0x59, 0x5f, 0x4d, 0x45, 0x54, 0x41, 0x5f, 0x47, 0x4c, 0x41, 0x53, 0x53, 0x45, 0x53, 0x10,
	0x02, 0x12, 0x15, 0x0a, 0x11, 0x48, 0x59, 0x50, 0x45, 0x52, 0x4e, 0x4f, 0x56, 0x41, 0x5f, 0x47,
	0x4c, 0x41, 0x53, 0x53, 0x45, 0x53, 0x10, 0x03, 0x1a, 0xfa, 0x02, 0x0a, 0x0d, 0x45, 0x78, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x52, 0x4c, 0x12, 0x54, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3c, 0x2e, 0x57, 0x41, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x65, 0x2e,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x11, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x46, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x55, 0x52, 0x4c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x55, 0x52, 0x4c, 0x22, 0xaa, 0x01, 0x0a, 0x06, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x0d, 0x0a, 0x09, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x47, 0x52, 0x41, 0x4d, 0x10, 0x01, 0x12,
	0x0c, 0x0a, 0x08, 0x46, 0x41, 0x43, 0x45, 0x42, 0x4f, 0x4f, 0x4b, 0x10, 0x02, 0x12, 0x0d, 0x0a,
	0x09, 0x4d, 0x45, 0x53, 0x53, 0x45, 0x4e, 0x47, 0x45, 0x52, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07,
	0x53, 0x50, 0x4f, 0x54, 0x49, 0x46, 0x59, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x59, 0x4f, 0x55,
	0x54, 0x55, 0x42, 0x45, 0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x49, 0x4e, 0x54, 0x45, 0x52,
	0x45, 0x53, 0x54, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x48, 0x52, 0x45, 0x41, 0x44, 0x53,
	0x10, 0x07, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x50, 0x50, 0x4c, 0x45, 0x5f, 0x4d, 0x55, 0x53, 0x49,
	0x43, 0x10, 0x08, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x48, 0x41, 0x52, 0x45, 0x43, 0x48, 0x41, 0x54,
	0x10, 0x09, 0x12, 0x11, 0x0a, 0x0d, 0x47, 0x4f, 0x4f, 0x47, 0x4c, 0x45, 0x5f, 0x50, 0x48, 0x4f,
	0x54, 0x4f, 0x53, 0x10, 0x0a, 0x1a, 0xcc, 0x03, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65, 0x12, 0x54, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3c, 0x2e, 0x57, 0x41, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x5a, 0x0a,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x3e, 0x2e, 0x57, 0x41, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0xa4, 0x01, 0x0a, 0x08, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4a, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4a,
	0x49, 0x44, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x44, 0x12, 0x30,
	0x0a, 0x13, 0x68, 0x61, 0x73, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x68, 0x61, 0x73,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65, 0x73,
	0x22, 0x62, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x49, 0x4e, 0x54, 0x45, 0x52,
	0x4e, 0x41, 0x4c, 0x5f, 0x52, 0x45, 0x53, 0x48, 0x41, 0x52, 0x45, 0x10, 0x01, 0x12, 0x13, 0x0a,
	0x0f, 0x4d, 0x45, 0x4e, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x52, 0x45, 0x53, 0x48, 0x41, 0x52, 0x45,
	0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x52, 0x45,
	0x53, 0x48, 0x41, 0x52, 0x45, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x4f, 0x52, 0x57, 0x41,
	0x52, 0x44, 0x10, 0x04, 0x1a, 0x2b, 0x0a, 0x0b, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4a, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4a, 0x49,
	0x44, 0x1a, 0xbb, 0x01, 0x0a, 0x05, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x12, 0x1e, 0x0a, 0x0a, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x6f, 0x6e, 0x67, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x6e,
	0x67, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x12, 0x2c, 0x0a, 0x11, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x61, 0x72,
	0x74, 0x69, 0x73, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1e, 0x0a, 0x0a, 0x69, 0x73, 0x45, 0x78, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x45, 0x78, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x22,
	0x96, 0x01, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x53, 0x48, 0x41, 0x52, 0x45,
	0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x58, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x53,
	0x48, 0x41, 0x52, 0x45, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x55, 0x53, 0x49, 0x43, 0x10,
	0x03, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4d, 0x45, 0x4e, 0x54,
	0x49, 0x4f, 0x4e, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x4c, 0x5f, 0x41, 0x54,
	0x54, 0x52, 0x49, 0x42, 0x55, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x06, 0x12, 0x0e, 0x0a, 0x0a, 0x41,
	0x49, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x07, 0x12, 0x0b, 0x0a, 0x07, 0x4c,
	0x41, 0x59, 0x4f, 0x55, 0x54, 0x53, 0x10, 0x08, 0x42, 0x11, 0x0a, 0x0f, 0x61, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x42, 0x30, 0x5a, 0x2e, 0x67,
	0x6f, 0x2e, 0x6d, 0x61, 0x75, 0x2e, 0x66, 0x69, 0x2f, 0x77, 0x68, 0x61, 0x74, 0x73, 0x6d, 0x65,
	0x6f, 0x77, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73,
}

var (
	file_waStatusAttributions_WAStatusAttributions_proto_rawDescOnce sync.Once
	file_waStatusAttributions_WAStatusAttributions_proto_rawDescData = file_waStatusAttributions_WAStatusAttributions_proto_rawDesc
)

func file_waStatusAttributions_WAStatusAttributions_proto_rawDescGZIP() []byte {
	file_waStatusAttributions_WAStatusAttributions_proto_rawDescOnce.Do(func() {
		file_waStatusAttributions_WAStatusAttributions_proto_rawDescData = protoimpl.X.CompressGZIP(file_waStatusAttributions_WAStatusAttributions_proto_rawDescData)
	})
	return file_waStatusAttributions_WAStatusAttributions_proto_rawDescData
}

var file_waStatusAttributions_WAStatusAttributions_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_waStatusAttributions_WAStatusAttributions_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_waStatusAttributions_WAStatusAttributions_proto_goTypes = []interface{}{
	(StatusAttribution_Type)(0),                        // 0: WAStatusAttributions.StatusAttribution.Type
	(StatusAttribution_AiCreatedAttribution_Source)(0), // 1: WAStatusAttributions.StatusAttribution.AiCreatedAttribution.Source
	(StatusAttribution_RLAttribution_Source)(0),        // 2: WAStatusAttributions.StatusAttribution.RLAttribution.Source
	(StatusAttribution_ExternalShare_Source)(0),        // 3: WAStatusAttributions.StatusAttribution.ExternalShare.Source
	(StatusAttribution_StatusReshare_Source)(0),        // 4: WAStatusAttributions.StatusAttribution.StatusReshare.Source
	(*StatusAttribution)(nil),                          // 5: WAStatusAttributions.StatusAttribution
	(*StatusAttribution_AiCreatedAttribution)(nil),     // 6: WAStatusAttributions.StatusAttribution.AiCreatedAttribution
	(*StatusAttribution_RLAttribution)(nil),            // 7: WAStatusAttributions.StatusAttribution.RLAttribution
	(*StatusAttribution_ExternalShare)(nil),            // 8: WAStatusAttributions.StatusAttribution.ExternalShare
	(*StatusAttribution_StatusReshare)(nil),            // 9: WAStatusAttributions.StatusAttribution.StatusReshare
	(*StatusAttribution_GroupStatus)(nil),              // 10: WAStatusAttributions.StatusAttribution.GroupStatus
	(*StatusAttribution_Music)(nil),                    // 11: WAStatusAttributions.StatusAttribution.Music
	(*StatusAttribution_StatusReshare_Metadata)(nil),   // 12: WAStatusAttributions.StatusAttribution.StatusReshare.Metadata
}
var file_waStatusAttributions_WAStatusAttributions_proto_depIdxs = []int32{
	9,  // 0: WAStatusAttributions.StatusAttribution.statusReshare:type_name -> WAStatusAttributions.StatusAttribution.StatusReshare
	8,  // 1: WAStatusAttributions.StatusAttribution.externalShare:type_name -> WAStatusAttributions.StatusAttribution.ExternalShare
	11, // 2: WAStatusAttributions.StatusAttribution.music:type_name -> WAStatusAttributions.StatusAttribution.Music
	10, // 3: WAStatusAttributions.StatusAttribution.groupStatus:type_name -> WAStatusAttributions.StatusAttribution.GroupStatus
	7,  // 4: WAStatusAttributions.StatusAttribution.rlAttribution:type_name -> WAStatusAttributions.StatusAttribution.RLAttribution
	6,  // 5: WAStatusAttributions.StatusAttribution.aiCreatedAttribution:type_name -> WAStatusAttributions.StatusAttribution.AiCreatedAttribution
	0,  // 6: WAStatusAttributions.StatusAttribution.type:type_name -> WAStatusAttributions.StatusAttribution.Type
	1,  // 7: WAStatusAttributions.StatusAttribution.AiCreatedAttribution.source:type_name -> WAStatusAttributions.StatusAttribution.AiCreatedAttribution.Source
	2,  // 8: WAStatusAttributions.StatusAttribution.RLAttribution.source:type_name -> WAStatusAttributions.StatusAttribution.RLAttribution.Source
	3,  // 9: WAStatusAttributions.StatusAttribution.ExternalShare.source:type_name -> WAStatusAttributions.StatusAttribution.ExternalShare.Source
	4,  // 10: WAStatusAttributions.StatusAttribution.StatusReshare.source:type_name -> WAStatusAttributions.StatusAttribution.StatusReshare.Source
	12, // 11: WAStatusAttributions.StatusAttribution.StatusReshare.metadata:type_name -> WAStatusAttributions.StatusAttribution.StatusReshare.Metadata
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_waStatusAttributions_WAStatusAttributions_proto_init() }
func file_waStatusAttributions_WAStatusAttributions_proto_init() {
	if File_waStatusAttributions_WAStatusAttributions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusAttribution); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusAttribution_AiCreatedAttribution); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusAttribution_RLAttribution); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusAttribution_ExternalShare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusAttribution_StatusReshare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusAttribution_GroupStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusAttribution_Music); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusAttribution_StatusReshare_Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_waStatusAttributions_WAStatusAttributions_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*StatusAttribution_StatusReshare_)(nil),
		(*StatusAttribution_ExternalShare_)(nil),
		(*StatusAttribution_Music_)(nil),
		(*StatusAttribution_GroupStatus_)(nil),
		(*StatusAttribution_RlAttribution)(nil),
		(*StatusAttribution_AiCreatedAttribution_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_waStatusAttributions_WAStatusAttributions_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_waStatusAttributions_WAStatusAttributions_proto_goTypes,
		DependencyIndexes: file_waStatusAttributions_WAStatusAttributions_proto_depIdxs,
		EnumInfos:         file_waStatusAttributions_WAStatusAttributions_proto_enumTypes,
		MessageInfos:      file_waStatusAttributions_WAStatusAttributions_proto_msgTypes,
	}.Build()
	File_waStatusAttributions_WAStatusAttributions_proto = out.File
	file_waStatusAttributions_WAStatusAttributions_proto_rawDesc = nil
	file_waStatusAttributions_WAStatusAttributions_proto_goTypes = nil
	file_waStatusAttributions_WAStatusAttributions_proto_depIdxs = nil
}
