// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: instamadilloCoreTypeAdminMessage/InstamadilloCoreTypeAdminMessage.proto

package instamadilloCoreTypeAdminMessage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceAdminMessage_Type int32

const (
	DeviceAdminMessage_DEVICE_ADMIN_MESSAGE_TYPE_NONE                                         DeviceAdminMessage_Type = 0
	DeviceAdminMessage_DEVICE_ADMIN_MESSAGE_TYPE_LOCAL_USER_CHANGED_IDENTITY_KEY_NAMED_DEVICE DeviceAdminMessage_Type = 1
	DeviceAdminMessage_DEVICE_ADMIN_MESSAGE_TYPE_SECURITY_ALERT_PARTICIPANT_KEY_CHANGE        DeviceAdminMessage_Type = 2
	DeviceAdminMessage_DEVICE_ADMIN_MESSAGE_TYPE_SECURITY_ALERT_PARTICIPANT_NEW_LOGIN         DeviceAdminMessage_Type = 3
)

// Enum value maps for DeviceAdminMessage_Type.
var (
	DeviceAdminMessage_Type_name = map[int32]string{
		0: "DEVICE_ADMIN_MESSAGE_TYPE_NONE",
		1: "DEVICE_ADMIN_MESSAGE_TYPE_LOCAL_USER_CHANGED_IDENTITY_KEY_NAMED_DEVICE",
		2: "DEVICE_ADMIN_MESSAGE_TYPE_SECURITY_ALERT_PARTICIPANT_KEY_CHANGE",
		3: "DEVICE_ADMIN_MESSAGE_TYPE_SECURITY_ALERT_PARTICIPANT_NEW_LOGIN",
	}
	DeviceAdminMessage_Type_value = map[string]int32{
		"DEVICE_ADMIN_MESSAGE_TYPE_NONE":                                         0,
		"DEVICE_ADMIN_MESSAGE_TYPE_LOCAL_USER_CHANGED_IDENTITY_KEY_NAMED_DEVICE": 1,
		"DEVICE_ADMIN_MESSAGE_TYPE_SECURITY_ALERT_PARTICIPANT_KEY_CHANGE":        2,
		"DEVICE_ADMIN_MESSAGE_TYPE_SECURITY_ALERT_PARTICIPANT_NEW_LOGIN":         3,
	}
)

func (x DeviceAdminMessage_Type) Enum() *DeviceAdminMessage_Type {
	p := new(DeviceAdminMessage_Type)
	*p = x
	return p
}

func (x DeviceAdminMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceAdminMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_enumTypes[0].Descriptor()
}

func (DeviceAdminMessage_Type) Type() protoreflect.EnumType {
	return &file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_enumTypes[0]
}

func (x DeviceAdminMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DeviceAdminMessage_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DeviceAdminMessage_Type(num)
	return nil
}

// Deprecated: Use DeviceAdminMessage_Type.Descriptor instead.
func (DeviceAdminMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_rawDescGZIP(), []int{1, 0}
}

type AdminMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to AdminMessageSubtype:
	//
	//	*AdminMessage_DeviceAdminMessage
	AdminMessageSubtype isAdminMessage_AdminMessageSubtype `protobuf_oneof:"adminMessageSubtype"`
}

func (x *AdminMessage) Reset() {
	*x = AdminMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminMessage) ProtoMessage() {}

func (x *AdminMessage) ProtoReflect() protoreflect.Message {
	mi := &file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminMessage.ProtoReflect.Descriptor instead.
func (*AdminMessage) Descriptor() ([]byte, []int) {
	return file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_rawDescGZIP(), []int{0}
}

func (m *AdminMessage) GetAdminMessageSubtype() isAdminMessage_AdminMessageSubtype {
	if m != nil {
		return m.AdminMessageSubtype
	}
	return nil
}

func (x *AdminMessage) GetDeviceAdminMessage() *DeviceAdminMessage {
	if x, ok := x.GetAdminMessageSubtype().(*AdminMessage_DeviceAdminMessage); ok {
		return x.DeviceAdminMessage
	}
	return nil
}

type isAdminMessage_AdminMessageSubtype interface {
	isAdminMessage_AdminMessageSubtype()
}

type AdminMessage_DeviceAdminMessage struct {
	DeviceAdminMessage *DeviceAdminMessage `protobuf:"bytes,1,opt,name=deviceAdminMessage,oneof"`
}

func (*AdminMessage_DeviceAdminMessage) isAdminMessage_AdminMessageSubtype() {}

type DeviceAdminMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceAdminMessageType *DeviceAdminMessage_Type `protobuf:"varint,1,opt,name=deviceAdminMessageType,enum=InstamadilloCoreTypeAdminMessage.DeviceAdminMessage_Type" json:"deviceAdminMessageType,omitempty"`
	DeviceName             *string                  `protobuf:"bytes,2,opt,name=deviceName" json:"deviceName,omitempty"`
}

func (x *DeviceAdminMessage) Reset() {
	*x = DeviceAdminMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceAdminMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceAdminMessage) ProtoMessage() {}

func (x *DeviceAdminMessage) ProtoReflect() protoreflect.Message {
	mi := &file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceAdminMessage.ProtoReflect.Descriptor instead.
func (*DeviceAdminMessage) Descriptor() ([]byte, []int) {
	return file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceAdminMessage) GetDeviceAdminMessageType() DeviceAdminMessage_Type {
	if x != nil && x.DeviceAdminMessageType != nil {
		return *x.DeviceAdminMessageType
	}
	return DeviceAdminMessage_DEVICE_ADMIN_MESSAGE_TYPE_NONE
}

func (x *DeviceAdminMessage) GetDeviceName() string {
	if x != nil && x.DeviceName != nil {
		return *x.DeviceName
	}
	return ""
}

var File_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto protoreflect.FileDescriptor

var file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_rawDesc = []byte{
	0x0a, 0x47, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x43, 0x6f,
	0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2f, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x43,
	0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x20, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x43, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x8d, 0x01, 0x0a, 0x0c,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x66, 0x0a, 0x12,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x43, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00,
	0x52, 0x12, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x42, 0x15, 0x0a, 0x13, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x53, 0x75, 0x62, 0x74, 0x79, 0x70, 0x65, 0x22, 0xa9, 0x03, 0x0a, 0x12,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x71, 0x0a, 0x16, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x39, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c,
	0x6f, 0x43, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x16, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xff, 0x01, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22,
	0x0a, 0x1e, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x5f, 0x4d,
	0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x4f, 0x4e, 0x45,
	0x10, 0x00, 0x12, 0x4a, 0x0a, 0x46, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x41, 0x44, 0x4d,
	0x49, 0x4e, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47,
	0x45, 0x44, 0x5f, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x5f, 0x4b, 0x45, 0x59, 0x5f,
	0x4e, 0x41, 0x4d, 0x45, 0x44, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x10, 0x01, 0x12, 0x43,
	0x0a, 0x3f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x5f, 0x4d,
	0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x45, 0x43, 0x55,
	0x52, 0x49, 0x54, 0x59, 0x5f, 0x41, 0x4c, 0x45, 0x52, 0x54, 0x5f, 0x50, 0x41, 0x52, 0x54, 0x49,
	0x43, 0x49, 0x50, 0x41, 0x4e, 0x54, 0x5f, 0x4b, 0x45, 0x59, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47,
	0x45, 0x10, 0x02, 0x12, 0x42, 0x0a, 0x3e, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x41, 0x44,
	0x4d, 0x49, 0x4e, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x53, 0x45, 0x43, 0x55, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x41, 0x4c, 0x45, 0x52, 0x54, 0x5f,
	0x50, 0x41, 0x52, 0x54, 0x49, 0x43, 0x49, 0x50, 0x41, 0x4e, 0x54, 0x5f, 0x4e, 0x45, 0x57, 0x5f,
	0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x03, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x6f, 0x2e, 0x6d, 0x61,
	0x75, 0x2e, 0x66, 0x69, 0x2f, 0x77, 0x68, 0x61, 0x74, 0x73, 0x6d, 0x65, 0x6f, 0x77, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6d, 0x61, 0x64, 0x69, 0x6c, 0x6c,
	0x6f, 0x43, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65,
}

var (
	file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_rawDescOnce sync.Once
	file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_rawDescData = file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_rawDesc
)

func file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_rawDescGZIP() []byte {
	file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_rawDescOnce.Do(func() {
		file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_rawDescData)
	})
	return file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_rawDescData
}

var file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_goTypes = []interface{}{
	(DeviceAdminMessage_Type)(0), // 0: InstamadilloCoreTypeAdminMessage.DeviceAdminMessage.Type
	(*AdminMessage)(nil),         // 1: InstamadilloCoreTypeAdminMessage.AdminMessage
	(*DeviceAdminMessage)(nil),   // 2: InstamadilloCoreTypeAdminMessage.DeviceAdminMessage
}
var file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_depIdxs = []int32{
	2, // 0: InstamadilloCoreTypeAdminMessage.AdminMessage.deviceAdminMessage:type_name -> InstamadilloCoreTypeAdminMessage.DeviceAdminMessage
	0, // 1: InstamadilloCoreTypeAdminMessage.DeviceAdminMessage.deviceAdminMessageType:type_name -> InstamadilloCoreTypeAdminMessage.DeviceAdminMessage.Type
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_init() }
func file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_init() {
	if File_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceAdminMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*AdminMessage_DeviceAdminMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_goTypes,
		DependencyIndexes: file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_depIdxs,
		EnumInfos:         file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_enumTypes,
		MessageInfos:      file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_msgTypes,
	}.Build()
	File_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto = out.File
	file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_rawDesc = nil
	file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_goTypes = nil
	file_instamadilloCoreTypeAdminMessage_InstamadilloCoreTypeAdminMessage_proto_depIdxs = nil
}
