// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: waDeviceCapabilities/WAWebProtobufsDeviceCapabilities.proto

package waDeviceCapabilities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceCapabilities_MemberNameTagPrimarySupport int32

const (
	DeviceCapabilities_DISABLED         DeviceCapabilities_MemberNameTagPrimarySupport = 0
	DeviceCapabilities_RECEIVER_ENABLED DeviceCapabilities_MemberNameTagPrimarySupport = 1
	DeviceCapabilities_SENDER_ENABLED   DeviceCapabilities_MemberNameTagPrimarySupport = 2
)

// Enum value maps for DeviceCapabilities_MemberNameTagPrimarySupport.
var (
	DeviceCapabilities_MemberNameTagPrimarySupport_name = map[int32]string{
		0: "DISABLED",
		1: "RECEIVER_ENABLED",
		2: "SENDER_ENABLED",
	}
	DeviceCapabilities_MemberNameTagPrimarySupport_value = map[string]int32{
		"DISABLED":         0,
		"RECEIVER_ENABLED": 1,
		"SENDER_ENABLED":   2,
	}
)

func (x DeviceCapabilities_MemberNameTagPrimarySupport) Enum() *DeviceCapabilities_MemberNameTagPrimarySupport {
	p := new(DeviceCapabilities_MemberNameTagPrimarySupport)
	*p = x
	return p
}

func (x DeviceCapabilities_MemberNameTagPrimarySupport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceCapabilities_MemberNameTagPrimarySupport) Descriptor() protoreflect.EnumDescriptor {
	return file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_enumTypes[0].Descriptor()
}

func (DeviceCapabilities_MemberNameTagPrimarySupport) Type() protoreflect.EnumType {
	return &file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_enumTypes[0]
}

func (x DeviceCapabilities_MemberNameTagPrimarySupport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DeviceCapabilities_MemberNameTagPrimarySupport) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DeviceCapabilities_MemberNameTagPrimarySupport(num)
	return nil
}

// Deprecated: Use DeviceCapabilities_MemberNameTagPrimarySupport.Descriptor instead.
func (DeviceCapabilities_MemberNameTagPrimarySupport) EnumDescriptor() ([]byte, []int) {
	return file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_rawDescGZIP(), []int{0, 0}
}

type DeviceCapabilities_ChatLockSupportLevel int32

const (
	DeviceCapabilities_NONE    DeviceCapabilities_ChatLockSupportLevel = 0
	DeviceCapabilities_MINIMAL DeviceCapabilities_ChatLockSupportLevel = 1
	DeviceCapabilities_FULL    DeviceCapabilities_ChatLockSupportLevel = 2
)

// Enum value maps for DeviceCapabilities_ChatLockSupportLevel.
var (
	DeviceCapabilities_ChatLockSupportLevel_name = map[int32]string{
		0: "NONE",
		1: "MINIMAL",
		2: "FULL",
	}
	DeviceCapabilities_ChatLockSupportLevel_value = map[string]int32{
		"NONE":    0,
		"MINIMAL": 1,
		"FULL":    2,
	}
)

func (x DeviceCapabilities_ChatLockSupportLevel) Enum() *DeviceCapabilities_ChatLockSupportLevel {
	p := new(DeviceCapabilities_ChatLockSupportLevel)
	*p = x
	return p
}

func (x DeviceCapabilities_ChatLockSupportLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceCapabilities_ChatLockSupportLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_enumTypes[1].Descriptor()
}

func (DeviceCapabilities_ChatLockSupportLevel) Type() protoreflect.EnumType {
	return &file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_enumTypes[1]
}

func (x DeviceCapabilities_ChatLockSupportLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DeviceCapabilities_ChatLockSupportLevel) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DeviceCapabilities_ChatLockSupportLevel(num)
	return nil
}

// Deprecated: Use DeviceCapabilities_ChatLockSupportLevel.Descriptor instead.
func (DeviceCapabilities_ChatLockSupportLevel) EnumDescriptor() ([]byte, []int) {
	return file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_rawDescGZIP(), []int{0, 1}
}

type DeviceCapabilities_AiThread_SupportLevel int32

const (
	DeviceCapabilities_AiThread_NONE  DeviceCapabilities_AiThread_SupportLevel = 0
	DeviceCapabilities_AiThread_INFRA DeviceCapabilities_AiThread_SupportLevel = 1
	DeviceCapabilities_AiThread_FULL  DeviceCapabilities_AiThread_SupportLevel = 2
)

// Enum value maps for DeviceCapabilities_AiThread_SupportLevel.
var (
	DeviceCapabilities_AiThread_SupportLevel_name = map[int32]string{
		0: "NONE",
		1: "INFRA",
		2: "FULL",
	}
	DeviceCapabilities_AiThread_SupportLevel_value = map[string]int32{
		"NONE":  0,
		"INFRA": 1,
		"FULL":  2,
	}
)

func (x DeviceCapabilities_AiThread_SupportLevel) Enum() *DeviceCapabilities_AiThread_SupportLevel {
	p := new(DeviceCapabilities_AiThread_SupportLevel)
	*p = x
	return p
}

func (x DeviceCapabilities_AiThread_SupportLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceCapabilities_AiThread_SupportLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_enumTypes[2].Descriptor()
}

func (DeviceCapabilities_AiThread_SupportLevel) Type() protoreflect.EnumType {
	return &file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_enumTypes[2]
}

func (x DeviceCapabilities_AiThread_SupportLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DeviceCapabilities_AiThread_SupportLevel) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DeviceCapabilities_AiThread_SupportLevel(num)
	return nil
}

// Deprecated: Use DeviceCapabilities_AiThread_SupportLevel.Descriptor instead.
func (DeviceCapabilities_AiThread_SupportLevel) EnumDescriptor() ([]byte, []int) {
	return file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_rawDescGZIP(), []int{0, 0, 0}
}

type DeviceCapabilities struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatLockSupportLevel        *DeviceCapabilities_ChatLockSupportLevel        `protobuf:"varint,1,opt,name=chatLockSupportLevel,enum=WAWebProtobufsDeviceCapabilities.DeviceCapabilities_ChatLockSupportLevel" json:"chatLockSupportLevel,omitempty"`
	LidMigration                *DeviceCapabilities_LIDMigration                `protobuf:"bytes,2,opt,name=lidMigration" json:"lidMigration,omitempty"`
	BusinessBroadcast           *DeviceCapabilities_BusinessBroadcast           `protobuf:"bytes,3,opt,name=businessBroadcast" json:"businessBroadcast,omitempty"`
	UserHasAvatar               *DeviceCapabilities_UserHasAvatar               `protobuf:"bytes,4,opt,name=userHasAvatar" json:"userHasAvatar,omitempty"`
	MemberNameTagPrimarySupport *DeviceCapabilities_MemberNameTagPrimarySupport `protobuf:"varint,5,opt,name=memberNameTagPrimarySupport,enum=WAWebProtobufsDeviceCapabilities.DeviceCapabilities_MemberNameTagPrimarySupport" json:"memberNameTagPrimarySupport,omitempty"`
	AiThread                    *DeviceCapabilities_AiThread                    `protobuf:"bytes,6,opt,name=aiThread" json:"aiThread,omitempty"`
}

func (x *DeviceCapabilities) Reset() {
	*x = DeviceCapabilities{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCapabilities) ProtoMessage() {}

func (x *DeviceCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCapabilities.ProtoReflect.Descriptor instead.
func (*DeviceCapabilities) Descriptor() ([]byte, []int) {
	return file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceCapabilities) GetChatLockSupportLevel() DeviceCapabilities_ChatLockSupportLevel {
	if x != nil && x.ChatLockSupportLevel != nil {
		return *x.ChatLockSupportLevel
	}
	return DeviceCapabilities_NONE
}

func (x *DeviceCapabilities) GetLidMigration() *DeviceCapabilities_LIDMigration {
	if x != nil {
		return x.LidMigration
	}
	return nil
}

func (x *DeviceCapabilities) GetBusinessBroadcast() *DeviceCapabilities_BusinessBroadcast {
	if x != nil {
		return x.BusinessBroadcast
	}
	return nil
}

func (x *DeviceCapabilities) GetUserHasAvatar() *DeviceCapabilities_UserHasAvatar {
	if x != nil {
		return x.UserHasAvatar
	}
	return nil
}

func (x *DeviceCapabilities) GetMemberNameTagPrimarySupport() DeviceCapabilities_MemberNameTagPrimarySupport {
	if x != nil && x.MemberNameTagPrimarySupport != nil {
		return *x.MemberNameTagPrimarySupport
	}
	return DeviceCapabilities_DISABLED
}

func (x *DeviceCapabilities) GetAiThread() *DeviceCapabilities_AiThread {
	if x != nil {
		return x.AiThread
	}
	return nil
}

type DeviceCapabilities_AiThread struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupportLevel *DeviceCapabilities_AiThread_SupportLevel `protobuf:"varint,1,opt,name=supportLevel,enum=WAWebProtobufsDeviceCapabilities.DeviceCapabilities_AiThread_SupportLevel" json:"supportLevel,omitempty"`
}

func (x *DeviceCapabilities_AiThread) Reset() {
	*x = DeviceCapabilities_AiThread{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceCapabilities_AiThread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCapabilities_AiThread) ProtoMessage() {}

func (x *DeviceCapabilities_AiThread) ProtoReflect() protoreflect.Message {
	mi := &file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCapabilities_AiThread.ProtoReflect.Descriptor instead.
func (*DeviceCapabilities_AiThread) Descriptor() ([]byte, []int) {
	return file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DeviceCapabilities_AiThread) GetSupportLevel() DeviceCapabilities_AiThread_SupportLevel {
	if x != nil && x.SupportLevel != nil {
		return *x.SupportLevel
	}
	return DeviceCapabilities_AiThread_NONE
}

type DeviceCapabilities_UserHasAvatar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserHasAvatar *bool `protobuf:"varint,1,opt,name=userHasAvatar" json:"userHasAvatar,omitempty"`
}

func (x *DeviceCapabilities_UserHasAvatar) Reset() {
	*x = DeviceCapabilities_UserHasAvatar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceCapabilities_UserHasAvatar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCapabilities_UserHasAvatar) ProtoMessage() {}

func (x *DeviceCapabilities_UserHasAvatar) ProtoReflect() protoreflect.Message {
	mi := &file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCapabilities_UserHasAvatar.ProtoReflect.Descriptor instead.
func (*DeviceCapabilities_UserHasAvatar) Descriptor() ([]byte, []int) {
	return file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_rawDescGZIP(), []int{0, 1}
}

func (x *DeviceCapabilities_UserHasAvatar) GetUserHasAvatar() bool {
	if x != nil && x.UserHasAvatar != nil {
		return *x.UserHasAvatar
	}
	return false
}

type DeviceCapabilities_BusinessBroadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImportListEnabled *bool `protobuf:"varint,1,opt,name=importListEnabled" json:"importListEnabled,omitempty"`
}

func (x *DeviceCapabilities_BusinessBroadcast) Reset() {
	*x = DeviceCapabilities_BusinessBroadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceCapabilities_BusinessBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCapabilities_BusinessBroadcast) ProtoMessage() {}

func (x *DeviceCapabilities_BusinessBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCapabilities_BusinessBroadcast.ProtoReflect.Descriptor instead.
func (*DeviceCapabilities_BusinessBroadcast) Descriptor() ([]byte, []int) {
	return file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_rawDescGZIP(), []int{0, 2}
}

func (x *DeviceCapabilities_BusinessBroadcast) GetImportListEnabled() bool {
	if x != nil && x.ImportListEnabled != nil {
		return *x.ImportListEnabled
	}
	return false
}

type DeviceCapabilities_LIDMigration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatDbMigrationTimestamp *uint64 `protobuf:"varint,1,opt,name=chatDbMigrationTimestamp" json:"chatDbMigrationTimestamp,omitempty"`
}

func (x *DeviceCapabilities_LIDMigration) Reset() {
	*x = DeviceCapabilities_LIDMigration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceCapabilities_LIDMigration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCapabilities_LIDMigration) ProtoMessage() {}

func (x *DeviceCapabilities_LIDMigration) ProtoReflect() protoreflect.Message {
	mi := &file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCapabilities_LIDMigration.ProtoReflect.Descriptor instead.
func (*DeviceCapabilities_LIDMigration) Descriptor() ([]byte, []int) {
	return file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_rawDescGZIP(), []int{0, 3}
}

func (x *DeviceCapabilities_LIDMigration) GetChatDbMigrationTimestamp() uint64 {
	if x != nil && x.ChatDbMigrationTimestamp != nil {
		return *x.ChatDbMigrationTimestamp
	}
	return 0
}

var File_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto protoreflect.FileDescriptor

var file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_rawDesc = []byte{
	0x0a, 0x3b, 0x77, 0x61, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2f, 0x57, 0x41, 0x57, 0x65, 0x62, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x73, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x61, 0x70, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x20, 0x57,
	0x41, 0x57, 0x65, 0x62, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22,
	0xcc, 0x09, 0x0a, 0x12, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x7d, 0x0a, 0x14, 0x63, 0x68, 0x61, 0x74, 0x4c, 0x6f,
	0x63, 0x6b, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x49, 0x2e, 0x57, 0x41, 0x57, 0x65, 0x62, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x73, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x61, 0x70, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x61,
	0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4c,
	0x6f, 0x63, 0x6b, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52,
	0x14, 0x63, 0x68, 0x61, 0x74, 0x4c, 0x6f, 0x63, 0x6b, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x65, 0x0a, 0x0c, 0x6c, 0x69, 0x64, 0x4d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x41, 0x2e, 0x57, 0x41,
	0x57, 0x65, 0x62, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x2e, 0x4c, 0x49, 0x44, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c,
	0x6c, 0x69, 0x64, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x74, 0x0a, 0x11,
	0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x46, 0x2e, 0x57, 0x41, 0x57, 0x65, 0x62, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x61,
	0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x42, 0x75,
	0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52,
	0x11, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x12, 0x68, 0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x48, 0x61, 0x73, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x42, 0x2e, 0x57, 0x41, 0x57, 0x65,
	0x62, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x48, 0x61, 0x73, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x0d, 0x75,
	0x73, 0x65, 0x72, 0x48, 0x61, 0x73, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x92, 0x01, 0x0a,
	0x1b, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x54, 0x61, 0x67, 0x50, 0x72,
	0x69, 0x6d, 0x61, 0x72, 0x79, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x50, 0x2e, 0x57, 0x41, 0x57, 0x65, 0x62, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x73, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x61, 0x70, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x54, 0x61, 0x67, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x53, 0x75, 0x70,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x1b, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x54, 0x61, 0x67, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72,
	0x74, 0x12, 0x59, 0x0a, 0x08, 0x61, 0x69, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x3d, 0x2e, 0x57, 0x41, 0x57, 0x65, 0x62, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x73, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x61, 0x70,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x41, 0x69, 0x54, 0x68, 0x72, 0x65,
	0x61, 0x64, 0x52, 0x08, 0x61, 0x69, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x1a, 0xa9, 0x01, 0x0a,
	0x08, 0x41, 0x69, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x12, 0x6e, 0x0a, 0x0c, 0x73, 0x75, 0x70,
	0x70, 0x6f, 0x72, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x4a, 0x2e, 0x57, 0x41, 0x57, 0x65, 0x62, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x41, 0x69, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x53,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x0c, 0x73, 0x75, 0x70,
	0x70, 0x6f, 0x72, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x2d, 0x0a, 0x0c, 0x53, 0x75, 0x70,
	0x70, 0x6f, 0x72, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e,
	0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4e, 0x46, 0x52, 0x41, 0x10, 0x01, 0x12, 0x08,
	0x0a, 0x04, 0x46, 0x55, 0x4c, 0x4c, 0x10, 0x02, 0x1a, 0x35, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72,
	0x48, 0x61, 0x73, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x75, 0x73, 0x65,
	0x72, 0x48, 0x61, 0x73, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x48, 0x61, 0x73, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x1a,
	0x41, 0x0a, 0x11, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x42, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x11, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x1a, 0x4a, 0x0a, 0x0c, 0x4c, 0x49, 0x44, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x3a, 0x0a, 0x18, 0x63, 0x68, 0x61, 0x74, 0x44, 0x62, 0x4d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x18, 0x63, 0x68, 0x61, 0x74, 0x44, 0x62, 0x4d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x55,
	0x0a, 0x1b, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x54, 0x61, 0x67, 0x50,
	0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x0c, 0x0a,
	0x08, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x52,
	0x45, 0x43, 0x45, 0x49, 0x56, 0x45, 0x52, 0x5f, 0x45, 0x4e, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10,
	0x01, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x45, 0x4e, 0x44, 0x45, 0x52, 0x5f, 0x45, 0x4e, 0x41, 0x42,
	0x4c, 0x45, 0x44, 0x10, 0x02, 0x22, 0x37, 0x0a, 0x14, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x6f, 0x63,
	0x6b, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x08, 0x0a,
	0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x49, 0x4e, 0x49, 0x4d,
	0x41, 0x4c, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x55, 0x4c, 0x4c, 0x10, 0x02, 0x42, 0x30,
	0x5a, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x61, 0x75, 0x2e, 0x66, 0x69, 0x2f, 0x77, 0x68, 0x61, 0x74,
	0x73, 0x6d, 0x65, 0x6f, 0x77, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73,
}

var (
	file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_rawDescOnce sync.Once
	file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_rawDescData = file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_rawDesc
)

func file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_rawDescGZIP() []byte {
	file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_rawDescOnce.Do(func() {
		file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_rawDescData = protoimpl.X.CompressGZIP(file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_rawDescData)
	})
	return file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_rawDescData
}

var file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_goTypes = []interface{}{
	(DeviceCapabilities_MemberNameTagPrimarySupport)(0), // 0: WAWebProtobufsDeviceCapabilities.DeviceCapabilities.MemberNameTagPrimarySupport
	(DeviceCapabilities_ChatLockSupportLevel)(0),        // 1: WAWebProtobufsDeviceCapabilities.DeviceCapabilities.ChatLockSupportLevel
	(DeviceCapabilities_AiThread_SupportLevel)(0),       // 2: WAWebProtobufsDeviceCapabilities.DeviceCapabilities.AiThread.SupportLevel
	(*DeviceCapabilities)(nil),                          // 3: WAWebProtobufsDeviceCapabilities.DeviceCapabilities
	(*DeviceCapabilities_AiThread)(nil),                 // 4: WAWebProtobufsDeviceCapabilities.DeviceCapabilities.AiThread
	(*DeviceCapabilities_UserHasAvatar)(nil),            // 5: WAWebProtobufsDeviceCapabilities.DeviceCapabilities.UserHasAvatar
	(*DeviceCapabilities_BusinessBroadcast)(nil),        // 6: WAWebProtobufsDeviceCapabilities.DeviceCapabilities.BusinessBroadcast
	(*DeviceCapabilities_LIDMigration)(nil),             // 7: WAWebProtobufsDeviceCapabilities.DeviceCapabilities.LIDMigration
}
var file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_depIdxs = []int32{
	1, // 0: WAWebProtobufsDeviceCapabilities.DeviceCapabilities.chatLockSupportLevel:type_name -> WAWebProtobufsDeviceCapabilities.DeviceCapabilities.ChatLockSupportLevel
	7, // 1: WAWebProtobufsDeviceCapabilities.DeviceCapabilities.lidMigration:type_name -> WAWebProtobufsDeviceCapabilities.DeviceCapabilities.LIDMigration
	6, // 2: WAWebProtobufsDeviceCapabilities.DeviceCapabilities.businessBroadcast:type_name -> WAWebProtobufsDeviceCapabilities.DeviceCapabilities.BusinessBroadcast
	5, // 3: WAWebProtobufsDeviceCapabilities.DeviceCapabilities.userHasAvatar:type_name -> WAWebProtobufsDeviceCapabilities.DeviceCapabilities.UserHasAvatar
	0, // 4: WAWebProtobufsDeviceCapabilities.DeviceCapabilities.memberNameTagPrimarySupport:type_name -> WAWebProtobufsDeviceCapabilities.DeviceCapabilities.MemberNameTagPrimarySupport
	4, // 5: WAWebProtobufsDeviceCapabilities.DeviceCapabilities.aiThread:type_name -> WAWebProtobufsDeviceCapabilities.DeviceCapabilities.AiThread
	2, // 6: WAWebProtobufsDeviceCapabilities.DeviceCapabilities.AiThread.supportLevel:type_name -> WAWebProtobufsDeviceCapabilities.DeviceCapabilities.AiThread.SupportLevel
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_init() }
func file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_init() {
	if File_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceCapabilities); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceCapabilities_AiThread); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceCapabilities_UserHasAvatar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceCapabilities_BusinessBroadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceCapabilities_LIDMigration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_goTypes,
		DependencyIndexes: file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_depIdxs,
		EnumInfos:         file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_enumTypes,
		MessageInfos:      file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_msgTypes,
	}.Build()
	File_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto = out.File
	file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_rawDesc = nil
	file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_goTypes = nil
	file_waDeviceCapabilities_WAWebProtobufsDeviceCapabilities_proto_depIdxs = nil
}
