// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: waCommon/WACommon.proto

package waCommon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FutureProofBehavior int32

const (
	FutureProofBehavior_PLACEHOLDER    FutureProofBehavior = 0
	FutureProofBehavior_NO_PLACEHOLDER FutureProofBehavior = 1
	FutureProofBehavior_IGNORE         FutureProofBehavior = 2
)

// Enum value maps for FutureProofBehavior.
var (
	FutureProofBehavior_name = map[int32]string{
		0: "PLACEHOLDER",
		1: "NO_PLACEHOLDER",
		2: "IGNORE",
	}
	FutureProofBehavior_value = map[string]int32{
		"PLACEHOLDER":    0,
		"NO_PLACEHOLDER": 1,
		"IGNORE":         2,
	}
)

func (x FutureProofBehavior) Enum() *FutureProofBehavior {
	p := new(FutureProofBehavior)
	*p = x
	return p
}

func (x FutureProofBehavior) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FutureProofBehavior) Descriptor() protoreflect.EnumDescriptor {
	return file_waCommon_WACommon_proto_enumTypes[0].Descriptor()
}

func (FutureProofBehavior) Type() protoreflect.EnumType {
	return &file_waCommon_WACommon_proto_enumTypes[0]
}

func (x FutureProofBehavior) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *FutureProofBehavior) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = FutureProofBehavior(num)
	return nil
}

// Deprecated: Use FutureProofBehavior.Descriptor instead.
func (FutureProofBehavior) EnumDescriptor() ([]byte, []int) {
	return file_waCommon_WACommon_proto_rawDescGZIP(), []int{0}
}

type Command_CommandType int32

const (
	Command_EVERYONE   Command_CommandType = 1
	Command_SILENT     Command_CommandType = 2
	Command_AI         Command_CommandType = 3
	Command_AI_IMAGINE Command_CommandType = 4
)

// Enum value maps for Command_CommandType.
var (
	Command_CommandType_name = map[int32]string{
		1: "EVERYONE",
		2: "SILENT",
		3: "AI",
		4: "AI_IMAGINE",
	}
	Command_CommandType_value = map[string]int32{
		"EVERYONE":   1,
		"SILENT":     2,
		"AI":         3,
		"AI_IMAGINE": 4,
	}
)

func (x Command_CommandType) Enum() *Command_CommandType {
	p := new(Command_CommandType)
	*p = x
	return p
}

func (x Command_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_waCommon_WACommon_proto_enumTypes[1].Descriptor()
}

func (Command_CommandType) Type() protoreflect.EnumType {
	return &file_waCommon_WACommon_proto_enumTypes[1]
}

func (x Command_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Command_CommandType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Command_CommandType(num)
	return nil
}

// Deprecated: Use Command_CommandType.Descriptor instead.
func (Command_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_waCommon_WACommon_proto_rawDescGZIP(), []int{1, 0}
}

type Mention_MentionType int32

const (
	Mention_PROFILE Mention_MentionType = 0
)

// Enum value maps for Mention_MentionType.
var (
	Mention_MentionType_name = map[int32]string{
		0: "PROFILE",
	}
	Mention_MentionType_value = map[string]int32{
		"PROFILE": 0,
	}
)

func (x Mention_MentionType) Enum() *Mention_MentionType {
	p := new(Mention_MentionType)
	*p = x
	return p
}

func (x Mention_MentionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mention_MentionType) Descriptor() protoreflect.EnumDescriptor {
	return file_waCommon_WACommon_proto_enumTypes[2].Descriptor()
}

func (Mention_MentionType) Type() protoreflect.EnumType {
	return &file_waCommon_WACommon_proto_enumTypes[2]
}

func (x Mention_MentionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Mention_MentionType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Mention_MentionType(num)
	return nil
}

// Deprecated: Use Mention_MentionType.Descriptor instead.
func (Mention_MentionType) EnumDescriptor() ([]byte, []int) {
	return file_waCommon_WACommon_proto_rawDescGZIP(), []int{2, 0}
}

type LimitSharing_Trigger int32

const (
	LimitSharing_UNKNOWN                 LimitSharing_Trigger = 0
	LimitSharing_CHAT_SETTING            LimitSharing_Trigger = 1
	LimitSharing_BIZ_SUPPORTS_FB_HOSTING LimitSharing_Trigger = 2
	LimitSharing_UNKNOWN_GROUP           LimitSharing_Trigger = 3
)

// Enum value maps for LimitSharing_Trigger.
var (
	LimitSharing_Trigger_name = map[int32]string{
		0: "UNKNOWN",
		1: "CHAT_SETTING",
		2: "BIZ_SUPPORTS_FB_HOSTING",
		3: "UNKNOWN_GROUP",
	}
	LimitSharing_Trigger_value = map[string]int32{
		"UNKNOWN":                 0,
		"CHAT_SETTING":            1,
		"BIZ_SUPPORTS_FB_HOSTING": 2,
		"UNKNOWN_GROUP":           3,
	}
)

func (x LimitSharing_Trigger) Enum() *LimitSharing_Trigger {
	p := new(LimitSharing_Trigger)
	*p = x
	return p
}

func (x LimitSharing_Trigger) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LimitSharing_Trigger) Descriptor() protoreflect.EnumDescriptor {
	return file_waCommon_WACommon_proto_enumTypes[3].Descriptor()
}

func (LimitSharing_Trigger) Type() protoreflect.EnumType {
	return &file_waCommon_WACommon_proto_enumTypes[3]
}

func (x LimitSharing_Trigger) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *LimitSharing_Trigger) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = LimitSharing_Trigger(num)
	return nil
}

// Deprecated: Use LimitSharing_Trigger.Descriptor instead.
func (LimitSharing_Trigger) EnumDescriptor() ([]byte, []int) {
	return file_waCommon_WACommon_proto_rawDescGZIP(), []int{5, 0}
}

type MessageKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteJID   *string `protobuf:"bytes,1,opt,name=remoteJID" json:"remoteJID,omitempty"`
	FromMe      *bool   `protobuf:"varint,2,opt,name=fromMe" json:"fromMe,omitempty"`
	ID          *string `protobuf:"bytes,3,opt,name=ID" json:"ID,omitempty"`
	Participant *string `protobuf:"bytes,4,opt,name=participant" json:"participant,omitempty"`
}

func (x *MessageKey) Reset() {
	*x = MessageKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waCommon_WACommon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageKey) ProtoMessage() {}

func (x *MessageKey) ProtoReflect() protoreflect.Message {
	mi := &file_waCommon_WACommon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageKey.ProtoReflect.Descriptor instead.
func (*MessageKey) Descriptor() ([]byte, []int) {
	return file_waCommon_WACommon_proto_rawDescGZIP(), []int{0}
}

func (x *MessageKey) GetRemoteJID() string {
	if x != nil && x.RemoteJID != nil {
		return *x.RemoteJID
	}
	return ""
}

func (x *MessageKey) GetFromMe() bool {
	if x != nil && x.FromMe != nil {
		return *x.FromMe
	}
	return false
}

func (x *MessageKey) GetID() string {
	if x != nil && x.ID != nil {
		return *x.ID
	}
	return ""
}

func (x *MessageKey) GetParticipant() string {
	if x != nil && x.Participant != nil {
		return *x.Participant
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandType     *Command_CommandType `protobuf:"varint,1,opt,name=commandType,enum=WACommon.Command_CommandType" json:"commandType,omitempty"`
	Offset          *uint32              `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Length          *uint32              `protobuf:"varint,3,opt,name=length" json:"length,omitempty"`
	ValidationToken *string              `protobuf:"bytes,4,opt,name=validationToken" json:"validationToken,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waCommon_WACommon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_waCommon_WACommon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_waCommon_WACommon_proto_rawDescGZIP(), []int{1}
}

func (x *Command) GetCommandType() Command_CommandType {
	if x != nil && x.CommandType != nil {
		return *x.CommandType
	}
	return Command_EVERYONE
}

func (x *Command) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *Command) GetLength() uint32 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

func (x *Command) GetValidationToken() string {
	if x != nil && x.ValidationToken != nil {
		return *x.ValidationToken
	}
	return ""
}

type Mention struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MentionType  *Mention_MentionType `protobuf:"varint,1,opt,name=mentionType,enum=WACommon.Mention_MentionType" json:"mentionType,omitempty"`
	MentionedJID *string              `protobuf:"bytes,2,opt,name=mentionedJID" json:"mentionedJID,omitempty"`
	Offset       *uint32              `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	Length       *uint32              `protobuf:"varint,4,opt,name=length" json:"length,omitempty"`
}

func (x *Mention) Reset() {
	*x = Mention{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waCommon_WACommon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mention) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mention) ProtoMessage() {}

func (x *Mention) ProtoReflect() protoreflect.Message {
	mi := &file_waCommon_WACommon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mention.ProtoReflect.Descriptor instead.
func (*Mention) Descriptor() ([]byte, []int) {
	return file_waCommon_WACommon_proto_rawDescGZIP(), []int{2}
}

func (x *Mention) GetMentionType() Mention_MentionType {
	if x != nil && x.MentionType != nil {
		return *x.MentionType
	}
	return Mention_PROFILE
}

func (x *Mention) GetMentionedJID() string {
	if x != nil && x.MentionedJID != nil {
		return *x.MentionedJID
	}
	return ""
}

func (x *Mention) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *Mention) GetLength() uint32 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

type MessageText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text         *string    `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	MentionedJID []string   `protobuf:"bytes,2,rep,name=mentionedJID" json:"mentionedJID,omitempty"`
	Commands     []*Command `protobuf:"bytes,3,rep,name=commands" json:"commands,omitempty"`
	Mentions     []*Mention `protobuf:"bytes,4,rep,name=mentions" json:"mentions,omitempty"`
}

func (x *MessageText) Reset() {
	*x = MessageText{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waCommon_WACommon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageText) ProtoMessage() {}

func (x *MessageText) ProtoReflect() protoreflect.Message {
	mi := &file_waCommon_WACommon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageText.ProtoReflect.Descriptor instead.
func (*MessageText) Descriptor() ([]byte, []int) {
	return file_waCommon_WACommon_proto_rawDescGZIP(), []int{3}
}

func (x *MessageText) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *MessageText) GetMentionedJID() []string {
	if x != nil {
		return x.MentionedJID
	}
	return nil
}

func (x *MessageText) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *MessageText) GetMentions() []*Mention {
	if x != nil {
		return x.Mentions
	}
	return nil
}

type SubProtocol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	Version *int32 `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
}

func (x *SubProtocol) Reset() {
	*x = SubProtocol{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waCommon_WACommon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubProtocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubProtocol) ProtoMessage() {}

func (x *SubProtocol) ProtoReflect() protoreflect.Message {
	mi := &file_waCommon_WACommon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubProtocol.ProtoReflect.Descriptor instead.
func (*SubProtocol) Descriptor() ([]byte, []int) {
	return file_waCommon_WACommon_proto_rawDescGZIP(), []int{4}
}

func (x *SubProtocol) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SubProtocol) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

type LimitSharing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SharingLimited               *bool                 `protobuf:"varint,1,opt,name=sharingLimited" json:"sharingLimited,omitempty"`
	Trigger                      *LimitSharing_Trigger `protobuf:"varint,2,opt,name=trigger,enum=WACommon.LimitSharing_Trigger" json:"trigger,omitempty"`
	LimitSharingSettingTimestamp *int64                `protobuf:"varint,3,opt,name=limitSharingSettingTimestamp" json:"limitSharingSettingTimestamp,omitempty"`
	InitiatedByMe                *bool                 `protobuf:"varint,4,opt,name=initiatedByMe" json:"initiatedByMe,omitempty"`
}

func (x *LimitSharing) Reset() {
	*x = LimitSharing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waCommon_WACommon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LimitSharing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitSharing) ProtoMessage() {}

func (x *LimitSharing) ProtoReflect() protoreflect.Message {
	mi := &file_waCommon_WACommon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitSharing.ProtoReflect.Descriptor instead.
func (*LimitSharing) Descriptor() ([]byte, []int) {
	return file_waCommon_WACommon_proto_rawDescGZIP(), []int{5}
}

func (x *LimitSharing) GetSharingLimited() bool {
	if x != nil && x.SharingLimited != nil {
		return *x.SharingLimited
	}
	return false
}

func (x *LimitSharing) GetTrigger() LimitSharing_Trigger {
	if x != nil && x.Trigger != nil {
		return *x.Trigger
	}
	return LimitSharing_UNKNOWN
}

func (x *LimitSharing) GetLimitSharingSettingTimestamp() int64 {
	if x != nil && x.LimitSharingSettingTimestamp != nil {
		return *x.LimitSharingSettingTimestamp
	}
	return 0
}

func (x *LimitSharing) GetInitiatedByMe() bool {
	if x != nil && x.InitiatedByMe != nil {
		return *x.InitiatedByMe
	}
	return false
}

var File_waCommon_WACommon_proto protoreflect.FileDescriptor

var file_waCommon_WACommon_proto_rawDesc = []byte{
	0x0a, 0x17, 0x77, 0x61, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x57, 0x41, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x57, 0x41, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x22, 0x74, 0x0a, 0x0a, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4b, 0x65,
	0x79, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x4a, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x4a, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x4d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x66, 0x72, 0x6f, 0x6d, 0x4d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x72, 0x74, 0x69,
	0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x22, 0xe5, 0x01, 0x0a, 0x07, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x3f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x57, 0x41, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x28, 0x0a, 0x0f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x3f, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0c, 0x0a, 0x08, 0x45, 0x56, 0x45, 0x52, 0x59, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x53, 0x49, 0x4c, 0x45, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02, 0x41, 0x49, 0x10,
	0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x49, 0x5f, 0x49, 0x4d, 0x41, 0x47, 0x49, 0x4e, 0x45, 0x10,
	0x04, 0x22, 0xba, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3f, 0x0a,
	0x0b, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x57, 0x41, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x65,
	0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0b, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22,
	0x0a, 0x0c, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x65, 0x64, 0x4a, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x65, 0x64, 0x4a,
	0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x22, 0x1a, 0x0a, 0x0b, 0x4d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x4f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x00, 0x22, 0xa3,
	0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x65, 0x78, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x65, 0x64, 0x4a,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f,
	0x6e, 0x65, 0x64, 0x4a, 0x49, 0x44, 0x12, 0x2d, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x57, 0x41, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x08, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x2d, 0x0a, 0x08, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x57, 0x41, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x4d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6d, 0x65, 0x6e, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x22, 0x41, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xb4, 0x02, 0x0a, 0x0c, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x53, 0x68, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x68, 0x61, 0x72,
	0x69, 0x6e, 0x67, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0e, 0x73, 0x68, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x64,
	0x12, 0x38, 0x0a, 0x07, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1e, 0x2e, 0x57, 0x41, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x53, 0x68, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65,
	0x72, 0x52, 0x07, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x12, 0x42, 0x0a, 0x1c, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x53, 0x68, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x1c, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x53, 0x68, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x24,
	0x0a, 0x0d, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x4d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x64,
	0x42, 0x79, 0x4d, 0x65, 0x22, 0x58, 0x0a, 0x07, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c,
	0x43, 0x48, 0x41, 0x54, 0x5f, 0x53, 0x45, 0x54, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x1b,
	0x0a, 0x17, 0x42, 0x49, 0x5a, 0x5f, 0x53, 0x55, 0x50, 0x50, 0x4f, 0x52, 0x54, 0x53, 0x5f, 0x46,
	0x42, 0x5f, 0x48, 0x4f, 0x53, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x10, 0x03, 0x2a, 0x46,
	0x0a, 0x13, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x42, 0x65, 0x68,
	0x61, 0x76, 0x69, 0x6f, 0x72, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x48, 0x4f,
	0x4c, 0x44, 0x45, 0x52, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4e, 0x4f, 0x5f, 0x50, 0x4c, 0x41,
	0x43, 0x45, 0x48, 0x4f, 0x4c, 0x44, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x47,
	0x4e, 0x4f, 0x52, 0x45, 0x10, 0x02, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x6f, 0x2e, 0x6d, 0x61, 0x75,
	0x2e, 0x66, 0x69, 0x2f, 0x77, 0x68, 0x61, 0x74, 0x73, 0x6d, 0x65, 0x6f, 0x77, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
}

var (
	file_waCommon_WACommon_proto_rawDescOnce sync.Once
	file_waCommon_WACommon_proto_rawDescData = file_waCommon_WACommon_proto_rawDesc
)

func file_waCommon_WACommon_proto_rawDescGZIP() []byte {
	file_waCommon_WACommon_proto_rawDescOnce.Do(func() {
		file_waCommon_WACommon_proto_rawDescData = protoimpl.X.CompressGZIP(file_waCommon_WACommon_proto_rawDescData)
	})
	return file_waCommon_WACommon_proto_rawDescData
}

var file_waCommon_WACommon_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_waCommon_WACommon_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_waCommon_WACommon_proto_goTypes = []interface{}{
	(FutureProofBehavior)(0),  // 0: WACommon.FutureProofBehavior
	(Command_CommandType)(0),  // 1: WACommon.Command.CommandType
	(Mention_MentionType)(0),  // 2: WACommon.Mention.MentionType
	(LimitSharing_Trigger)(0), // 3: WACommon.LimitSharing.Trigger
	(*MessageKey)(nil),        // 4: WACommon.MessageKey
	(*Command)(nil),           // 5: WACommon.Command
	(*Mention)(nil),           // 6: WACommon.Mention
	(*MessageText)(nil),       // 7: WACommon.MessageText
	(*SubProtocol)(nil),       // 8: WACommon.SubProtocol
	(*LimitSharing)(nil),      // 9: WACommon.LimitSharing
}
var file_waCommon_WACommon_proto_depIdxs = []int32{
	1, // 0: WACommon.Command.commandType:type_name -> WACommon.Command.CommandType
	2, // 1: WACommon.Mention.mentionType:type_name -> WACommon.Mention.MentionType
	5, // 2: WACommon.MessageText.commands:type_name -> WACommon.Command
	6, // 3: WACommon.MessageText.mentions:type_name -> WACommon.Mention
	3, // 4: WACommon.LimitSharing.trigger:type_name -> WACommon.LimitSharing.Trigger
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_waCommon_WACommon_proto_init() }
func file_waCommon_WACommon_proto_init() {
	if File_waCommon_WACommon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_waCommon_WACommon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waCommon_WACommon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waCommon_WACommon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mention); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waCommon_WACommon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageText); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waCommon_WACommon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubProtocol); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waCommon_WACommon_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LimitSharing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_waCommon_WACommon_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_waCommon_WACommon_proto_goTypes,
		DependencyIndexes: file_waCommon_WACommon_proto_depIdxs,
		EnumInfos:         file_waCommon_WACommon_proto_enumTypes,
		MessageInfos:      file_waCommon_WACommon_proto_msgTypes,
	}.Build()
	File_waCommon_WACommon_proto = out.File
	file_waCommon_WACommon_proto_rawDesc = nil
	file_waCommon_WACommon_proto_goTypes = nil
	file_waCommon_WACommon_proto_depIdxs = nil
}
